displayName=Varrock Stray Cats
author=UnCorny
description=Give Varrock's stray dogs healthy, cat, pet, boss, Wise Old Man or cabbage appearances.
tags=cat,cats,dog,dogs,pets,boss,varrock,duke,cosmetic
plugins=com.cornydonkeh.varrockstraycats.VarrockStrayCatsPlugin
version=1.0.0
build=standard
