package com.cornydonkeh.varrockstraycats;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.function.Predicate;
import net.runelite.api.gameval.AnimationID;
import net.runelite.api.gameval.ItemID;
import net.runelite.api.gameval.NpcID;

/** Generated offline from a reviewed cache catalogue; see docs/appearances.md. */
enum AppearanceVariant
{
    BERNESEPUPPYCHOCOLATE(NpcID.SHEPARD_CHOCO_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::bernesePuppyChocolate),
    BERNESEPUPPYMERLE(NpcID.SHEPARD_MERLE_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::bernesePuppyMerle),
    BERNESEPUPPYTOASTED(NpcID.SHEPARD_TOASTED_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::bernesePuppyToasted),
    BERNESEADULTCHOCOLATE(NpcID.SHEPARD_CHOCO, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::berneseAdultChocolate),
    BERNESEADULTMERLE(NpcID.SHEPARD_MERLE, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::berneseAdultMerle),
    BERNESEADULTTOASTED(NpcID.SHEPARD_TOASTED, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::berneseAdultToasted),
    BORDERCOLLIEPUPPYCHOCOLATE(NpcID.COLLIE_CHOCO_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::borderColliePuppyChocolate),
    BORDERCOLLIEPUPPYMERLE(NpcID.COLLIE_MERLE_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::borderColliePuppyMerle),
    BORDERCOLLIEPUPPYBLACKWHITE(NpcID.COLLIE_BW_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::borderColliePuppyBlackWhite),
    BORDERCOLLIEADULTCHOCOLATE(NpcID.COLLIE_CHOCO, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::borderCollieAdultChocolate),
    BORDERCOLLIEADULTMERLE(NpcID.COLLIE_MERLE, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::borderCollieAdultMerle),
    BORDERCOLLIEADULTBLACKWHITE(NpcID.COLLIE_BW, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::borderCollieAdultBlackWhite),
    CHIHUAHUAPUPPYTAN(NpcID.CHIHUAHUA_TAN_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY_SIMPLE, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::chihuahuaPuppyTan),
    CHIHUAHUAPUPPYWHITE(NpcID.CHIHUAHUA_WHITE_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY_SIMPLE, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::chihuahuaPuppyWhite),
    CHIHUAHUAPUPPYTOASTED(NpcID.CHIHUAHUA_TOASTED_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY_SIMPLE, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::chihuahuaPuppyToasted),
    CHIHUAHUAADULTTAN(NpcID.CHIHUAHUA_TAN, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::chihuahuaAdultTan),
    CHIHUAHUAADULTWHITE(NpcID.CHIHUAHUA_WHITE, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::chihuahuaAdultWhite),
    CHIHUAHUAADULTTOASTED(NpcID.CHIHUAHUA_TOASTED, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::chihuahuaAdultToasted),
    CORGIPUPPYTAN(NpcID.CORGI_TAN_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::corgiPuppyTan),
    CORGIPUPPYFAWN(NpcID.CORGI_YELLOW_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::corgiPuppyFawn),
    CORGIPUPPYTOASTED(NpcID.CORGI_TOASTED_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::corgiPuppyToasted),
    CORGIADULTTAN(NpcID.CORGI_TAN, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::corgiAdultTan),
    CORGIADULTFAWN(NpcID.CORGI_YELLOW, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::corgiAdultFawn),
    CORGIADULTTOASTED(NpcID.CORGI_TOASTED, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::corgiAdultToasted),
    GREYHOUNDPUPPYTAN(NpcID.GREYHOUND_TAN_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::greyhoundPuppyTan),
    GREYHOUNDPUPPYGREY(NpcID.GREYHOUND_GREY_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::greyhoundPuppyGrey),
    GREYHOUNDPUPPYCREAM(NpcID.GREYHOUND_CREAM_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::greyhoundPuppyCream),
    GREYHOUNDADULTTAN(NpcID.GREYHOUND_TAN, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::greyhoundAdultTan),
    GREYHOUNDADULTGREY(NpcID.GREYHOUND_GREY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::greyhoundAdultGrey),
    GREYHOUNDADULTCREAM(NpcID.GREYHOUND_CREAM, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::greyhoundAdultCream),
    HUSKYPUPPYBLACKWHITE(NpcID.HUSKY_BW_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::huskyPuppyBlackWhite),
    HUSKYPUPPYGREY(NpcID.HUSKY_GREY_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::huskyPuppyGrey),
    HUSKYPUPPYCHOCOLATE(NpcID.HUSKY_CHOCO_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::huskyPuppyChocolate),
    HUSKYADULTBLACKWHITE(NpcID.HUSKY_BW, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::huskyAdultBlackWhite),
    HUSKYADULTGREY(NpcID.HUSKY_GREY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::huskyAdultGrey),
    HUSKYADULTCHOCOLATE(NpcID.HUSKY_CHOCO, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::huskyAdultChocolate),
    LABRADORPUPPYGOLDEN(NpcID.LABRADOR_YELLOW_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY_SIMPLE, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::labradorPuppyGolden),
    LABRADORPUPPYCHOCOLATE(NpcID.LABRADOR_CHOCO_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY_SIMPLE, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::labradorPuppyChocolate),
    LABRADORPUPPYBLACK(NpcID.LABRADOR_BLACK_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY_SIMPLE, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::labradorPuppyBlack),
    LABRADORADULTGOLDEN(NpcID.LABRADOR_YELLOW, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::labradorAdultGolden),
    LABRADORADULTCHOCOLATE(NpcID.LABRADOR_BROWN, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::labradorAdultChocolate),
    LABRADORADULTBLACK(NpcID.LABRADOR_BLACK, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::labradorAdultBlack),
    PUGPUPPYFAWN(NpcID.PUG_FAWN_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::pugPuppyFawn),
    PUGPUPPYBROWN(NpcID.PUG_BROWN_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::pugPuppyBrown),
    PUGPUPPYBLACK(NpcID.PUG_BLACK_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::pugPuppyBlack),
    PUGADULTFAWN(NpcID.PUG_FAWN, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::pugAdultFawn),
    PUGADULTBROWN(NpcID.PUG_BROWN, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::pugAdultBrown),
    PUGADULTBLACK(NpcID.PUG_BLACK, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::pugAdultBlack),
    SAMOYEDPUPPYWHITE(NpcID.SAMOYED_WHITE_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::samoyedPuppyWhite),
    SAMOYEDPUPPYGOLDEN(NpcID.SAMOYED_YELLOW_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::samoyedPuppyGolden),
    SAMOYEDPUPPYBLACK(NpcID.SAMOYED_BLACK_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::samoyedPuppyBlack),
    SAMOYEDADULTWHITE(NpcID.SAMOYED_WHITE, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::samoyedAdultWhite),
    SAMOYEDADULTGOLDEN(NpcID.SAMOYED_YELLOW, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::samoyedAdultGolden),
    SAMOYEDADULTBLACK(NpcID.SAMOYED_BLACK, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::samoyedAdultBlack),
    SHIBAPUPPYTAN(NpcID.SHIBA_TAN_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::shibaPuppyTan),
    SHIBAPUPPYWHITE(NpcID.SHIBA_WHITE_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::shibaPuppyWhite),
    SHIBAPUPPYTOASTED(NpcID.SHIBA_TOASTED_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::shibaPuppyToasted),
    SHIBAADULTTAN(NpcID.SHIBA_TAN, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::shibaAdultTan),
    SHIBAADULTWHITE(NpcID.SHIBA_WHITE, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::shibaAdultWhite),
    SHIBAADULTTOASTED(NpcID.SHIBA_TOASTED, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::shibaAdultToasted),
    SPANIELPUPPYRED(NpcID.SPANIEL_RED_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::spanielPuppyRed),
    SPANIELPUPPYWHITE(NpcID.SPANIEL_WHITE_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::spanielPuppyWhite),
    SPANIELPUPPYBLACK(NpcID.SPANIEL_BLACK_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::spanielPuppyBlack),
    SPANIELADULTRED(NpcID.SPANIEL_RED, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::spanielAdultRed),
    SPANIELADULTWHITE(NpcID.SPANIEL_WHITE, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::spanielAdultWhite),
    SPANIELADULTBLACK(NpcID.SPANIEL_BLACK, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::spanielAdultBlack),
    YORKIEPUPPYBROWN(NpcID.YORKIE_BROWN_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::yorkiePuppyBrown),
    YORKIEPUPPYWHITE(NpcID.YORKIE_WHITE_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::yorkiePuppyWhite),
    YORKIEPUPPYGOLDEN(NpcID.YORKIE_YELLOW_PUPPY, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::yorkiePuppyGolden),
    YORKIEADULTBROWN(NpcID.YORKIE_BROWN, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::yorkieAdultBrown),
    YORKIEADULTWHITE(NpcID.YORKIE_WHITE, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::yorkieAdultWhite),
    YORKIEADULTGOLDEN(NpcID.YORKIE_YELLOW, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::yorkieAdultGolden),
    APPEARANCEGROWNCAT(NpcID.GROWNCAT, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceGrowncat),
    APPEARANCEGROWNCATLIGHT(NpcID.GROWNCAT_LIGHT, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceGrowncatLight),
    APPEARANCEGROWNCATBROWN(NpcID.GROWNCAT_BROWN, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceGrowncatBrown),
    APPEARANCEGROWNCATBLACK(NpcID.GROWNCAT_BLACK, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceGrowncatBlack),
    APPEARANCEGROWNCATBROWNGREY(NpcID.GROWNCAT_BROWNGREY, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceGrowncatBrowngrey),
    APPEARANCEGROWNCATBLUEGREY(NpcID.GROWNCAT_BLUEGREY, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceGrowncatBluegrey),
    APPEARANCEGROWNCATHELL(NpcID.GROWNCAT_HELL, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceGrowncatHell),
    APPEARANCELAZYCATLIGHT(NpcID.LAZYCAT_LIGHT, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceLazycatLight),
    APPEARANCELAZYCAT(NpcID.LAZYCAT, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceLazycat),
    APPEARANCELAZYCATBROWN(NpcID.LAZYCAT_BROWN, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceLazycatBrown),
    APPEARANCELAZYCATBLACK(NpcID.LAZYCAT_BLACK, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceLazycatBlack),
    APPEARANCELAZYCATBROWNGREY(NpcID.LAZYCAT_BROWNGREY, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceLazycatBrowngrey),
    APPEARANCELAZYCATBLUEGREY(NpcID.LAZYCAT_BLUEGREY, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceLazycatBluegrey),
    APPEARANCELAZYCATHELL(NpcID.LAZYCAT_HELL, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceLazycatHell),
    APPEARANCEWILEYCATLIGHT(NpcID.WILEYCAT_LIGHT, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceWileycatLight),
    APPEARANCEWILEYCAT(NpcID.WILEYCAT, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceWileycat),
    APPEARANCEWILEYCATBROWN(NpcID.WILEYCAT_BROWN, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceWileycatBrown),
    APPEARANCEWILEYCATBLACK(NpcID.WILEYCAT_BLACK, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceWileycatBlack),
    APPEARANCEWILEYCATBROWNGREY(NpcID.WILEYCAT_BROWNGREY, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceWileycatBrowngrey),
    APPEARANCEWILEYCATBLUEGREY(NpcID.WILEYCAT_BLUEGREY, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceWileycatBluegrey),
    APPEARANCEWILEYCATHELL(NpcID.WILEYCAT_HELL, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceWileycatHell),
    APPEARANCEKITTENPET1(NpcID.KITTENPET1, false, AnimationID.CAT_READY, AnimationID.KITTEN_WALK, null, null, VarrockStrayCatsConfig::appearanceKittenpet1),
    APPEARANCEKITTENPETLIGHT(NpcID.KITTENPET_LIGHT, false, AnimationID.CAT_READY, AnimationID.KITTEN_WALK, null, null, VarrockStrayCatsConfig::appearanceKittenpetLight),
    APPEARANCEKITTENPETBROWN(NpcID.KITTENPET_BROWN, false, AnimationID.CAT_READY, AnimationID.KITTEN_WALK, null, null, VarrockStrayCatsConfig::appearanceKittenpetBrown),
    APPEARANCEKITTENPETBLACK(NpcID.KITTENPET_BLACK, false, AnimationID.CAT_READY, AnimationID.KITTEN_WALK, null, null, VarrockStrayCatsConfig::appearanceKittenpetBlack),
    APPEARANCEKITTENPETBROWNGREY(NpcID.KITTENPET_BROWNGREY, false, AnimationID.CAT_READY, AnimationID.KITTEN_WALK, null, null, VarrockStrayCatsConfig::appearanceKittenpetBrowngrey),
    APPEARANCEKITTENPETBLUEGREY(NpcID.KITTENPET_BLUEGREY, false, AnimationID.CAT_READY, AnimationID.KITTEN_WALK, null, null, VarrockStrayCatsConfig::appearanceKittenpetBluegrey),
    APPEARANCEKITTENPETHELL(NpcID.KITTENPET_HELL, false, AnimationID.CAT_READY, AnimationID.KITTEN_WALK, null, null, VarrockStrayCatsConfig::appearanceKittenpetHell),
    APPEARANCEOVERGROWNCAT(NpcID.OVERGROWNCAT, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceOvergrowncat),
    APPEARANCEOVERGROWNCATLIGHT(NpcID.OVERGROWNCAT_LIGHT, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceOvergrowncatLight),
    APPEARANCEOVERGROWNCATBROWN(NpcID.OVERGROWNCAT_BROWN, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceOvergrowncatBrown),
    APPEARANCEOVERGROWNCATBLACK(NpcID.OVERGROWNCAT_BLACK, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceOvergrowncatBlack),
    APPEARANCEOVERGROWNCATBROWNGREY(NpcID.OVERGROWNCAT_BROWNGREY, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceOvergrowncatBrowngrey),
    APPEARANCEOVERGROWNCATBLUEGREY(NpcID.OVERGROWNCAT_BLUEGREY, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceOvergrowncatBluegrey),
    APPEARANCEOVERGROWNCATHELL(NpcID.OVERGROWNCAT_HELL, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceOvergrowncatHell),
    APPEARANCECOREPET(NpcID.CORE_PET, false, AnimationID.DARKCORE_IDLE_PET, AnimationID.DARKCORE_WALK, null, null, VarrockStrayCatsConfig::appearanceCorePet),
    APPEARANCECHAOSELEMENTALPET(NpcID.CHAOS_ELEMENTAL_PET, false, AnimationID.CHAOSELEMENTAL_READY, AnimationID.CHAOSELEMENTAL_WALK, null, null, VarrockStrayCatsConfig::appearanceChaosElementalPet),
    APPEARANCESNAKEPETGREEN(NpcID.SNAKE_PET_GREEN, false, AnimationID.SNAKEBOSS_PET_IDLE, AnimationID.SNAKEBOSS_PET_WALK_FORWARD, null, null, VarrockStrayCatsConfig::appearanceSnakePetGreen),
    APPEARANCESNAKEPETORANGE(NpcID.SNAKE_PET_ORANGE, false, AnimationID.SNAKEBOSS_PET_IDLE, AnimationID.SNAKEBOSS_PET_WALK_FORWARD, null, null, VarrockStrayCatsConfig::appearanceSnakePetOrange),
    APPEARANCESNAKEPETBLUE(NpcID.SNAKE_PET_BLUE, false, AnimationID.SNAKEBOSS_PET_IDLE, AnimationID.SNAKEBOSS_PET_WALK_FORWARD, null, null, VarrockStrayCatsConfig::appearanceSnakePetBlue),
    APPEARANCESARACHNISPET(NpcID.SARACHNISPET, false, AnimationID.HOSDUN_SPIDER_BOSS_IDLE, AnimationID.HODSUN_SPIDER_BOSS_WALK, null, null, VarrockStrayCatsConfig::appearanceSarachnispet),
    APPEARANCEPOHTOYCAT(NpcID.POH_TOY_CAT, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearancePohToyCat),
    APPEARANCEPHOENIXPETGREEN(NpcID.PHOENIX_PET_GREEN, false, AnimationID.FIREBIRD_UPDATE_READY, AnimationID.FIREBIRD_UPDATE_FLY, null, null, VarrockStrayCatsConfig::appearancePhoenixPetGreen),
    APPEARANCEPHOENIXPETBLUE(NpcID.PHOENIX_PET_BLUE, false, AnimationID.FIREBIRD_UPDATE_READY, AnimationID.FIREBIRD_UPDATE_FLY, null, null, VarrockStrayCatsConfig::appearancePhoenixPetBlue),
    APPEARANCEPHOENIXPETWHITE(NpcID.PHOENIX_PET_WHITE, false, AnimationID.FIREBIRD_UPDATE_READY, AnimationID.FIREBIRD_UPDATE_FLY, null, null, VarrockStrayCatsConfig::appearancePhoenixPetWhite),
    APPEARANCEPHOENIXPETPURPLE(NpcID.PHOENIX_PET_PURPLE, false, AnimationID.FIREBIRD_UPDATE_READY, AnimationID.FIREBIRD_UPDATE_FLY, null, null, VarrockStrayCatsConfig::appearancePhoenixPetPurple),
    APPEARANCEHELLPET(NpcID.HELLPET, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::appearanceHellpet),
    APPEARANCESOULWARSPETBLUE(NpcID.SOULWARS_PET_BLUE, false, AnimationID.SNP_NATURE_BOSS_READY, AnimationID.SNP_NATURE_BOSS_PET_WALK, null, null, VarrockStrayCatsConfig::appearanceSoulwarsPetBlue),
    APPEARANCECHOMPYBIRDPET(NpcID.CHOMPY_BIRD_PET, false, AnimationID.CHOMPY_UPDATE_READY_AND_EXTRA, AnimationID.CHOMPY_UPDATE_WALK, null, null, VarrockStrayCatsConfig::appearanceChompyBirdPet),
    APPEARANCESOULWARSPETRED(NpcID.SOULWARS_PET_RED, false, AnimationID.SNP_FIRE_BOSS_READY, AnimationID.SNP_FIRE_BOSS_PET_WALK, null, null, VarrockStrayCatsConfig::appearanceSoulwarsPetRed),
    APPEARANCEVENENATISPET(NpcID.VENENATISPET, false, AnimationID.NPC_VENENATIS_IDLE_01, AnimationID.NPC_VENENATIS_WALK_01, null, null, VarrockStrayCatsConfig::appearanceVenenatispet),
    APPEARANCECALLISTOPET(NpcID.CALLISTOPET, false, AnimationID.NPC_CALLISTO_IDLE01, AnimationID.NPC_CALLISTO_PET_WALK01, null, null, VarrockStrayCatsConfig::appearanceCallistopet),
    APPEARANCEVETIONPET(NpcID.VETIONPET, false, AnimationID.NPC_VETION_IDLE_01, AnimationID.NPC_VETION_WALK_01, null, null, VarrockStrayCatsConfig::appearanceVetionpet),
    APPEARANCEVETIONPET2(NpcID.VETIONPET_2, false, AnimationID.NPC_VETION_IDLE_01, AnimationID.NPC_VETION_WALK_01, null, null, VarrockStrayCatsConfig::appearanceVetionpet2),
    APPEARANCESCORPIAPET(NpcID.SCORPIAPET, false, AnimationID.SMALL_SCORPION_UPDATE_READY, AnimationID.SMALL_SCORPION_UPDATE_WALK, null, null, VarrockStrayCatsConfig::appearanceScorpiapet),
    APPEARANCEABYSSALSIREPET(NpcID.ABYSSALSIRE_PET, false, AnimationID.ABYSSAL_SCION_IDLE, AnimationID.ABYSSAL_SCION_WALK, null, null, VarrockStrayCatsConfig::appearanceAbyssalsirePet),
    APPEARANCEJADPET(NpcID.JADPET, false, AnimationID.LORDMAGMUS_READY, AnimationID.JAD_BOSS_PET_WALK, null, null, VarrockStrayCatsConfig::appearanceJadpet),
    APPEARANCESUPREMEPET(NpcID.SUPREME_PET, false, AnimationID.DAGANNOTH_MEGANOTH_READY, AnimationID.DAGANNOTH_MEGANOTH_WALK, null, null, VarrockStrayCatsConfig::appearanceSupremePet),
    APPEARANCEPRIMEPET(NpcID.PRIME_PET, false, AnimationID.DAGANNOTH_MEGANOTH_READY, AnimationID.DAGANNOTH_MEGANOTH_WALK, null, null, VarrockStrayCatsConfig::appearancePrimePet),
    APPEARANCEREXPET(NpcID.REX_PET, false, AnimationID.DAGANNOTH_MEGANOTH_READY, AnimationID.DAGANNOTH_MEGANOTH_WALK, null, null, VarrockStrayCatsConfig::appearanceRexPet),
    APPEARANCEARMADYLPET(NpcID.ARMADYL_PET, false, AnimationID.GODWARS_ARMADYL_PET_READY, AnimationID.GODWARS_ARMADYL_PET_WALK, null, null, VarrockStrayCatsConfig::appearanceArmadylPet),
    APPEARANCEBANDOSPET(NpcID.BANDOS_PET, false, AnimationID.GODWARS_BANDOS_READY, AnimationID.GODWARS_BANDOS_WALK, null, null, VarrockStrayCatsConfig::appearanceBandosPet),
    APPEARANCESARADOMINPET(NpcID.SARADOMIN_PET, false, AnimationID.GODWARS_SARADOMIN_READY, AnimationID.GODWARS_SARADOMIN_WALK, null, null, VarrockStrayCatsConfig::appearanceSaradominPet),
    APPEARANCEZAMORAKPET(NpcID.ZAMORAK_PET, false, AnimationID.GODWARS_ZAMORAK_READY, AnimationID.GODWARS_ZAMORAK_WALK, null, null, VarrockStrayCatsConfig::appearanceZamorakPet),
    APPEARANCEMOLEPET(NpcID.MOLE_PET, false, AnimationID.MOLE_READY, AnimationID.MOLE_WALK, null, null, VarrockStrayCatsConfig::appearanceMolePet),
    APPEARANCEKBDPET(NpcID.KBD_PET, false, AnimationID.DRAGON_READY, AnimationID.DRAGON_WALK_KBD, null, null, VarrockStrayCatsConfig::appearanceKbdPet),
    APPEARANCEKQPETFLYING(NpcID.KQ_PET_FLYING, false, AnimationID.KALPHITE_UPDATE_FLYING_QUEEN_READY_WALK, AnimationID.KALPHITE_UPDATE_FLYING_QUEEN_READY_WALK, null, null, VarrockStrayCatsConfig::appearanceKqPetFlying),
    APPEARANCEKQPETWALKING(NpcID.KQ_PET_WALKING, false, AnimationID.KALPHITE_UPDATE_QUEEN_READY, AnimationID.KALPHITE_UPDATE_QUEEN_WALK, null, null, VarrockStrayCatsConfig::appearanceKqPetWalking),
    APPEARANCESMOKEPET(NpcID.SMOKE_PET, false, AnimationID.LORE_DUST_DEVIL_READY, AnimationID.LORE_DUST_DEVIL_WALK, null, null, VarrockStrayCatsConfig::appearanceSmokePet),
    APPEARANCEKRAKENPET(NpcID.KRAKEN_PET, false, AnimationID.SWAN_QUEEN_READY, AnimationID.SWAN_QUEEN_READY, null, null, VarrockStrayCatsConfig::appearanceKrakenPet),
    APPEARANCEPENANCEPET(NpcID.PENANCE_PET, false, AnimationID.BARBASSAULT_PENACNE_QUEEN_NEW_READY, AnimationID.BARBASSAULT_PENANCE_QUEEN_NEW_WALK, null, null, VarrockStrayCatsConfig::appearancePenancePet),
    APPEARANCESKILLPETFISH(NpcID.SKILLPET_FISH, false, AnimationID.BIRD_FLYING_UPDATE_READY_AND_EXTRA_TOUCAN_AND_CORMARANT, AnimationID.BIRD_FLYING_UPDATE_READY_TOUCAN_AND_CORMARANT, null, null, VarrockStrayCatsConfig::appearanceSkillpetFish),
    APPEARANCESKILLPETHUNTERRED(NpcID.SKILLPET_HUNTER_RED, false, AnimationID.HUNTING_CHINCHOMPA_READY, AnimationID.HUNTING_CHINCHOMPA_WALKING, null, null, VarrockStrayCatsConfig::appearanceSkillpetHunterRed),
    APPEARANCESKILLPETHUNTERGREY(NpcID.SKILLPET_HUNTER_GREY, false, AnimationID.HUNTING_CHINCHOMPA_READY, AnimationID.HUNTING_CHINCHOMPA_WALKING, null, null, VarrockStrayCatsConfig::appearanceSkillpetHunterGrey),
    APPEARANCESKILLPETHUNTERBLACK(NpcID.SKILLPET_HUNTER_BLACK, false, AnimationID.HUNTING_CHINCHOMPA_READY, AnimationID.HUNTING_CHINCHOMPA_WALKING, null, null, VarrockStrayCatsConfig::appearanceSkillpetHunterBlack),
    APPEARANCESKILLPETHUNTERGOLD(NpcID.SKILLPET_HUNTER_GOLD, false, AnimationID.HUNTING_CHINCHOMPA_READY, AnimationID.HUNTING_CHINCHOMPA_WALKING, null, null, VarrockStrayCatsConfig::appearanceSkillpetHunterGold),
    APPEARANCEBLOODHOUNDPET(NpcID.BLOODHOUNDPET, false, AnimationID.LORE_DOG_READY, AnimationID.BLOODHOUND_WALK, null, null, VarrockStrayCatsConfig::appearanceBloodhoundpet),
    APPEARANCESKILLPETAGILITY(NpcID.SKILLPET_AGILITY, false, AnimationID.SQUIRREL_IDLE, AnimationID.SQUIRREL_HOP, null, null, VarrockStrayCatsConfig::appearanceSkillpetAgility),
    APPEARANCESKILLPETFARMING(NpcID.SKILLPET_FARMING, false, AnimationID.TANGLEROOT_IDLE, AnimationID.TANGLEROOT_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetFarming),
    APPEARANCESKILLPETTHIEVING(NpcID.SKILLPET_THIEVING, false, AnimationID.RACCOON_IDLE, AnimationID.RACCOON_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetThieving),
    APPEARANCESKILLPETRUNECRAFTINGFIRE(NpcID.SKILLPET_RUNECRAFTING_FIRE, false, AnimationID.RIFT_GUARDIAN_IDLE, AnimationID.RIFT_GUARDIAN_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetRunecraftingFire),
    APPEARANCESKILLPETRUNECRAFTINGAIR(NpcID.SKILLPET_RUNECRAFTING_AIR, false, AnimationID.RIFT_GUARDIAN_IDLE, AnimationID.RIFT_GUARDIAN_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetRunecraftingAir),
    APPEARANCESKILLPETRUNECRAFTINGMIND(NpcID.SKILLPET_RUNECRAFTING_MIND, false, AnimationID.RIFT_GUARDIAN_IDLE, AnimationID.RIFT_GUARDIAN_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetRunecraftingMind),
    APPEARANCESKILLPETRUNECRAFTINGWATER(NpcID.SKILLPET_RUNECRAFTING_WATER, false, AnimationID.RIFT_GUARDIAN_IDLE, AnimationID.RIFT_GUARDIAN_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetRunecraftingWater),
    APPEARANCESKILLPETRUNECRAFTINGEARTH(NpcID.SKILLPET_RUNECRAFTING_EARTH, false, AnimationID.RIFT_GUARDIAN_IDLE, AnimationID.RIFT_GUARDIAN_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetRunecraftingEarth),
    APPEARANCESKILLPETRUNECRAFTINGBODY(NpcID.SKILLPET_RUNECRAFTING_BODY, false, AnimationID.RIFT_GUARDIAN_IDLE, AnimationID.RIFT_GUARDIAN_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetRunecraftingBody),
    APPEARANCESKILLPETRUNECRAFTINGCOSMIC(NpcID.SKILLPET_RUNECRAFTING_COSMIC, false, AnimationID.RIFT_GUARDIAN_IDLE, AnimationID.RIFT_GUARDIAN_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetRunecraftingCosmic),
    APPEARANCESKILLPETRUNECRAFTINGCHAOS(NpcID.SKILLPET_RUNECRAFTING_CHAOS, false, AnimationID.RIFT_GUARDIAN_IDLE, AnimationID.RIFT_GUARDIAN_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetRunecraftingChaos),
    APPEARANCESKILLPETRUNECRAFTINGNATURE(NpcID.SKILLPET_RUNECRAFTING_NATURE, false, AnimationID.RIFT_GUARDIAN_IDLE, AnimationID.RIFT_GUARDIAN_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetRunecraftingNature),
    APPEARANCESKILLPETRUNECRAFTINGLAW(NpcID.SKILLPET_RUNECRAFTING_LAW, false, AnimationID.RIFT_GUARDIAN_IDLE, AnimationID.RIFT_GUARDIAN_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetRunecraftingLaw),
    APPEARANCESKILLPETRUNECRAFTINGDEATH(NpcID.SKILLPET_RUNECRAFTING_DEATH, false, AnimationID.RIFT_GUARDIAN_IDLE, AnimationID.RIFT_GUARDIAN_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetRunecraftingDeath),
    APPEARANCESKILLPETRUNECRAFTINGSOUL(NpcID.SKILLPET_RUNECRAFTING_SOUL, false, AnimationID.RIFT_GUARDIAN_IDLE, AnimationID.RIFT_GUARDIAN_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetRunecraftingSoul),
    APPEARANCESKILLPETRUNECRAFTINGASTRAL(NpcID.SKILLPET_RUNECRAFTING_ASTRAL, false, AnimationID.RIFT_GUARDIAN_IDLE, AnimationID.RIFT_GUARDIAN_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetRunecraftingAstral),
    APPEARANCESKILLPETRUNECRAFTINGBLOOD(NpcID.SKILLPET_RUNECRAFTING_BLOOD, false, AnimationID.RIFT_GUARDIAN_IDLE, AnimationID.RIFT_GUARDIAN_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetRunecraftingBlood),
    APPEARANCEPHOENIXPET(NpcID.PHOENIX_PET, false, AnimationID.FIREBIRD_UPDATE_READY, AnimationID.FIREBIRD_UPDATE_FLY, null, null, VarrockStrayCatsConfig::appearancePhoenixPet),
    APPEARANCESKILLPETMININGDEFAULT(NpcID.SKILLPET_MINING_DEFAULT, false, AnimationID.ROCK_GOLEM_IDLE, AnimationID.ROCK_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetMiningDefault),
    APPEARANCESKILLPETMININGTIN(NpcID.SKILLPET_MINING_TIN, false, AnimationID.ROCK_GOLEM_IDLE, AnimationID.ROCK_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetMiningTin),
    APPEARANCESKILLPETMININGCOPPER(NpcID.SKILLPET_MINING_COPPER, false, AnimationID.ROCK_GOLEM_IDLE, AnimationID.ROCK_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetMiningCopper),
    APPEARANCESKILLPETMININGIRON(NpcID.SKILLPET_MINING_IRON, false, AnimationID.ROCK_GOLEM_IDLE, AnimationID.ROCK_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetMiningIron),
    APPEARANCESKILLPETMININGBLURITE(NpcID.SKILLPET_MINING_BLURITE, false, AnimationID.ROCK_GOLEM_IDLE, AnimationID.ROCK_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetMiningBlurite),
    APPEARANCERAIDSOLMPET(NpcID.RAIDS_OLM_PET, false, AnimationID.OLM_PET_IDLE, AnimationID.OLM_PET_WALK, null, null, VarrockStrayCatsConfig::appearanceRaidsOlmPet),
    APPEARANCESCURRIUSPET(NpcID.SCURRIUS_PET, false, AnimationID.NPC_RAT_BOSS_IDLE_01, AnimationID.PET_RAT_BOSS_WALK_01, null, null, VarrockStrayCatsConfig::appearanceScurriusPet),
    APPEARANCESKILLPETMININGSILVER(NpcID.SKILLPET_MINING_SILVER, false, AnimationID.ROCK_GOLEM_IDLE, AnimationID.ROCK_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetMiningSilver),
    APPEARANCESKILLPETMININGCOAL(NpcID.SKILLPET_MINING_COAL, false, AnimationID.ROCK_GOLEM_IDLE, AnimationID.ROCK_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetMiningCoal),
    APPEARANCESKILLPETMININGGOLD(NpcID.SKILLPET_MINING_GOLD, false, AnimationID.ROCK_GOLEM_IDLE, AnimationID.ROCK_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetMiningGold),
    APPEARANCESKILLPETMININGMITHRIL(NpcID.SKILLPET_MINING_MITHRIL, false, AnimationID.ROCK_GOLEM_IDLE, AnimationID.ROCK_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetMiningMithril),
    APPEARANCESKILLPETMININGGRANITE(NpcID.SKILLPET_MINING_GRANITE, false, AnimationID.ROCK_GOLEM_IDLE, AnimationID.ROCK_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetMiningGranite),
    APPEARANCESKILLPETMININGADAMANTITE(NpcID.SKILLPET_MINING_ADAMANTITE, false, AnimationID.ROCK_GOLEM_IDLE, AnimationID.ROCK_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetMiningAdamantite),
    APPEARANCESKILLPETMININGRUNITE(NpcID.SKILLPET_MINING_RUNITE, false, AnimationID.ROCK_GOLEM_IDLE, AnimationID.ROCK_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetMiningRunite),
    APPEARANCESKOTIZOPET(NpcID.SKOTIZO_PET, false, AnimationID.GODWARS_ZAMORAK_READY, AnimationID.GODWARS_ZAMORAK_WALK, null, null, VarrockStrayCatsConfig::appearanceSkotizoPet),
    APPEARANCEINFERNOPET(NpcID.INFERNO_PET, false, AnimationID.JALNIB_READY, AnimationID.JALNIB_WALK, null, null, VarrockStrayCatsConfig::appearanceInfernoPet),
    APPEARANCESKILLPETMININGAMETHYST(NpcID.SKILLPET_MINING_AMETHYST, false, AnimationID.ROCK_GOLEM_IDLE, AnimationID.ROCK_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetMiningAmethyst),
    APPEARANCESKILLPETMININGLOVAKITE(NpcID.SKILLPET_MINING_LOVAKITE, false, AnimationID.ROCK_GOLEM_IDLE, AnimationID.ROCK_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetMiningLovakite),
    APPEARANCESKILLPETMININGELEMENTAL(NpcID.SKILLPET_MINING_ELEMENTAL, false, AnimationID.ROCK_GOLEM_IDLE, AnimationID.ROCK_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetMiningElemental),
    APPEARANCESKILLPETMININGDAEYALT(NpcID.SKILLPET_MINING_DAEYALT, false, AnimationID.ROCK_GOLEM_IDLE, AnimationID.ROCK_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetMiningDaeyalt),
    APPEARANCEHERBIBOARPET(NpcID.HERBIBOAR_PET, false, AnimationID.FOSSIL_NPC_HERBIBOAR_IDLE, AnimationID.FOSSIL_NPC_HERBIBOAR_WALK, null, null, VarrockStrayCatsConfig::appearanceHerbiboarPet),
    APPEARANCEDAWNPET(NpcID.DAWN_PET, false, AnimationID.GG_DAWN_FLY, AnimationID.GG_DAWN_FLY, null, null, VarrockStrayCatsConfig::appearanceDawnPet),
    APPEARANCEDUSKPET(NpcID.DUSK_PET, false, AnimationID.GG_DUSK_PET_IDLE, AnimationID.GG_DUSK_PET_WALK, null, null, VarrockStrayCatsConfig::appearanceDuskPet),
    APPEARANCECORPPET(NpcID.CORP_PET, false, AnimationID.CORPBEAST_IDLE, AnimationID.CORPBEAST_WALK_IMPROVED, null, null, VarrockStrayCatsConfig::appearanceCorpPet),
    APPEARANCEZUKPET(NpcID.ZUK_PET, false, AnimationID.ZUKREK_IDLE, AnimationID.ZUKREK_WALK, null, null, VarrockStrayCatsConfig::appearanceZukPet),
    APPEARANCESKILLPETRUNECRAFTINGWRATH(NpcID.SKILLPET_RUNECRAFTING_WRATH, false, AnimationID.RIFT_GUARDIAN_IDLE, AnimationID.RIFT_GUARDIAN_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetRunecraftingWrath),
    APPEARANCEVORKATHPET(NpcID.VORKATH_PET, false, AnimationID.DS2_VORKATH_IDLE, AnimationID.DS2_VORKATH_PET_WALK, null, null, VarrockStrayCatsConfig::appearanceVorkathPet),
    APPEARANCEDOGADILEPET(NpcID.DOGADILE_PET, false, AnimationID.DOHGADYLE_IDLE, AnimationID.DOGADILE_PET_WALK, null, null, VarrockStrayCatsConfig::appearanceDogadilePet),
    APPEARANCETEKTONPET(NpcID.TEKTON_PET, false, AnimationID.TEKTON_IDLE, AnimationID.TEKTON_PET_WALK, null, null, VarrockStrayCatsConfig::appearanceTektonPet),
    APPEARANCEVANGUARDPET(NpcID.VANGUARD_PET, false, AnimationID.VANGUARD_IDLE_BASIC, AnimationID.VANGUARD_PET_WALK, null, null, VarrockStrayCatsConfig::appearanceVanguardPet),
    APPEARANCEVASAPET(NpcID.VASA_PET, false, AnimationID.VASA_IDLE, AnimationID.VASA_PET_WALK, null, null, VarrockStrayCatsConfig::appearanceVasaPet),
    APPEARANCEVESPULAPET(NpcID.VESPULA_PET, false, AnimationID.VESPULA_IDLE, AnimationID.VESPULA_PET_WALK, null, null, VarrockStrayCatsConfig::appearanceVespulaPet),
    APPEARANCEVERZIKPET(NpcID.VERZIK_PET, false, AnimationID.VERZIK_PHASE3_IDLE_PET, AnimationID.VERZIK_PHASE3_WALK_PET, null, null, VarrockStrayCatsConfig::appearanceVerzikPet),
    APPEARANCESMOKEPETOLD(NpcID.SMOKE_PET_OLD, false, AnimationID.LORE_DUST_DEVIL_READY, AnimationID.LORE_DUST_DEVIL_WALK, null, null, VarrockStrayCatsConfig::appearanceSmokePetOld),
    APPEARANCEHYDRAPET(NpcID.HYDRA_PET, false, AnimationID.HYDRA_STAGE_1_READY, AnimationID.HYDRA_STAGE_1_WALK_SILENT, null, null, VarrockStrayCatsConfig::appearanceHydraPet),
    APPEARANCEHYDRAPETELECTRIC(NpcID.HYDRA_PET_ELECTRIC, false, AnimationID.HYDRA_STAGE_2_READY_SILENT, AnimationID.HYDRA_STAGE_2_WALK_SILENT, null, null, VarrockStrayCatsConfig::appearanceHydraPetElectric),
    APPEARANCEHYDRAPETFIRE(NpcID.HYDRA_PET_FIRE, false, AnimationID.HYDRA_STAGE_3_READY, AnimationID.HYDRA_STAGE_3_WALK_SILENT, null, null, VarrockStrayCatsConfig::appearanceHydraPetFire),
    APPEARANCEHYDRAPETEXTINGUISHED(NpcID.HYDRA_PET_EXTINGUISHED, false, AnimationID.HYDRA_STAGE_4_READY, AnimationID.HYDRA_STAGE_4_WALK_SILENT, null, null, VarrockStrayCatsConfig::appearanceHydraPetExtinguished),
    APPEARANCENIGHTMAREPETPARASITE(NpcID.NIGHTMARE_PET_PARASITE, false, AnimationID.NIGHTMARE_PARASITE_IDLE, AnimationID.NIGHTMARE_PARASITE_IDLE, null, null, VarrockStrayCatsConfig::appearanceNightmarePetParasite),
    APPEARANCEGAUNTLETPET(NpcID.GAUNTLET_PET, false, AnimationID.HUNLLEF_READY, AnimationID.HUNLLEF_PET_WALK, null, null, VarrockStrayCatsConfig::appearanceGauntletPet),
    APPEARANCEGAUNTLETPETCORRUPT(NpcID.GAUNTLET_PET_CORRUPT, false, AnimationID.HUNLLEF_READY, AnimationID.HUNLLEF_PET_WALK, null, null, VarrockStrayCatsConfig::appearanceGauntletPetCorrupt),
    APPEARANCEZALCANOPET(NpcID.ZALCANO_PET, false, AnimationID.ZALCANO_IDLE, AnimationID.ZALCANO_PET_WALK, null, null, VarrockStrayCatsConfig::appearanceZalcanoPet),
    APPEARANCENIGHTMAREPET(NpcID.NIGHTMARE_PET, false, AnimationID.NIGHTMARE_IDLE, AnimationID.NIGHTMARE_PET_WALK, null, null, VarrockStrayCatsConfig::appearanceNightmarePet),
    APPEARANCESKILLPETFARMINGCRYSTAL(NpcID.SKILLPET_FARMING_CRYSTAL, false, AnimationID.TANGLEROOT_IDLE, AnimationID.TANGLEROOT_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetFarmingCrystal),
    APPEARANCESKILLPETFARMINGDRAGON(NpcID.SKILLPET_FARMING_DRAGON, false, AnimationID.TANGLEROOT_IDLE, AnimationID.TANGLEROOT_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetFarmingDragon),
    APPEARANCESKILLPETFARMINGHERB(NpcID.SKILLPET_FARMING_HERB, false, AnimationID.TANGLEROOT_IDLE, AnimationID.TANGLEROOT_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetFarmingHerb),
    APPEARANCESKILLPETFARMINGLILY(NpcID.SKILLPET_FARMING_LILY, false, AnimationID.TANGLEROOT_IDLE, AnimationID.TANGLEROOT_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetFarmingLily),
    APPEARANCESKILLPETFARMINGREDWOOD(NpcID.SKILLPET_FARMING_REDWOOD, false, AnimationID.TANGLEROOT_IDLE, AnimationID.TANGLEROOT_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetFarmingRedwood),
    APPEARANCETEKTONENRAGEDPET(NpcID.TEKTON_ENRAGED_PET, false, AnimationID.TEKTON_IDLE_ENRAGED, AnimationID.TEKTON_ENRAGED_PET_WALK, null, null, VarrockStrayCatsConfig::appearanceTektonEnragedPet),
    APPEARANCEVESPULAFLYINGPET(NpcID.VESPULA_FLYING_PET, false, AnimationID.VESPULA_PET_FLY, AnimationID.VESPULA_PET_FLY, null, null, VarrockStrayCatsConfig::appearanceVespulaFlyingPet),
    APPEARANCESKILLPETAGILITYDARK(NpcID.SKILLPET_AGILITY_DARK, false, AnimationID.SQUIRREL_IDLE, AnimationID.SQUIRREL_HOP, null, null, VarrockStrayCatsConfig::appearanceSkillpetAgilityDark),
    APPEARANCESKILLPETTHIEVINGPANDA(NpcID.SKILLPET_THIEVING_PANDA, false, AnimationID.RACCOON_IDLE, AnimationID.RACCOON_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetThievingPanda),
    APPEARANCESKILLPETTHIEVINGTANUKI(NpcID.SKILLPET_THIEVING_TANUKI, false, AnimationID.RACCOON_IDLE, AnimationID.RACCOON_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetThievingTanuki),
    APPEARANCEJADPETINFERNO(NpcID.JADPET_INFERNO, false, AnimationID.JALTOKJAD_READY, AnimationID.JALTOKJAD_WALK_PET, null, null, VarrockStrayCatsConfig::appearanceJadpetInferno),
    APPEARANCESKILLPETFISHTEMPOROSS(NpcID.SKILLPET_FISH_TEMPOROSS, false, AnimationID.BIRD_FLYING_UPDATE_READY_AND_EXTRA_TOUCAN_AND_CORMARANT, AnimationID.BIRD_FLYING_UPDATE_READY_TOUCAN_AND_CORMARANT, null, null, VarrockStrayCatsConfig::appearanceSkillpetFishTempoross),
    APPEARANCETEMPOROSSPET(NpcID.TEMPOROSS_PET, false, AnimationID.FSB_READY, AnimationID.FSB_READY, null, null, VarrockStrayCatsConfig::appearanceTemporossPet),
    APPEARANCEMOLEPETNAKED(NpcID.MOLE_PET_NAKED, false, AnimationID.MOLE_READY, AnimationID.MOLE_WALK, null, null, VarrockStrayCatsConfig::appearanceMolePetNaked),
    APPEARANCEVERZIKPETMAIDEN(NpcID.VERZIK_PET_MAIDEN, false, AnimationID.MAIDEN_PET_IDLE, AnimationID.MAIDEN_PET_IDLE, null, null, VarrockStrayCatsConfig::appearanceVerzikPetMaiden),
    APPEARANCEVERZIKPETBLOAT(NpcID.VERZIK_PET_BLOAT, false, AnimationID.TOB_BLOAT_READY, AnimationID.TOB_BLOAT_WALK_PET, null, null, VarrockStrayCatsConfig::appearanceVerzikPetBloat),
    APPEARANCEVERZIKPETNYLOCAS(NpcID.VERZIK_PET_NYLOCAS, false, AnimationID.TOP_SPIDER_MELEE_IDLE, AnimationID.TOP_SPIDER_MELEE_WALK, null, null, VarrockStrayCatsConfig::appearanceVerzikPetNylocas),
    APPEARANCEVERZIKPETSOTETSEG(NpcID.VERZIK_PET_SOTETSEG, false, AnimationID.TOB_SOTETSEG_IDLE, AnimationID.TOB_SOTETSEG_WALK_PET, null, null, VarrockStrayCatsConfig::appearanceVerzikPetSotetseg),
    APPEARANCEVERZIKPETXARPUS(NpcID.VERZIK_PET_XARPUS, false, AnimationID.TOB_XARPUS_PET_IDLE, AnimationID.TOB_XARPUS_PET_IDLE, null, null, VarrockStrayCatsConfig::appearanceVerzikPetXarpus),
    APPEARANCESARACHNISPETORANGE(NpcID.SARACHNISPET_ORANGE, false, AnimationID.HOSDUN_SPIDER_BOSS_IDLE, AnimationID.HODSUN_SPIDER_BOSS_WALK, null, null, VarrockStrayCatsConfig::appearanceSarachnispetOrange),
    APPEARANCESARACHNISPETBLUE(NpcID.SARACHNISPET_BLUE, false, AnimationID.HOSDUN_SPIDER_BOSS_IDLE, AnimationID.HODSUN_SPIDER_BOSS_WALK, null, null, VarrockStrayCatsConfig::appearanceSarachnispetBlue),
    APPEARANCENEXPET(NpcID.NEX_PET, false, AnimationID.NEX_READY, AnimationID.NEX_PET_RUN, null, null, VarrockStrayCatsConfig::appearanceNexPet),
    APPEARANCESKILLPETRUNECRAFTINGGOTR(NpcID.SKILLPET_RUNECRAFTING_GOTR, false, AnimationID.RIFT_GUARDIAN_READY, AnimationID.RIFT_GUARDIAN_WALK_SMALL, null, null, VarrockStrayCatsConfig::appearanceSkillpetRunecraftingGotr),
    APPEARANCEABYSSALPET(NpcID.ABYSSAL_PET, false, AnimationID.ABYSSAL_PYRAMID_READY, AnimationID.ABYSSAL_PYRAMID_WALK, null, null, VarrockStrayCatsConfig::appearanceAbyssalPet),
    APPEARANCEWARDENPETTUMEKEN(NpcID.WARDEN_PET_TUMEKEN, false, AnimationID.NPC_WARDENS_IDLE03, AnimationID.NPC_WARDENS_WALK03, null, null, VarrockStrayCatsConfig::appearanceWardenPetTumeken),
    APPEARANCEWARDENPETELIDINIS(NpcID.WARDEN_PET_ELIDINIS, false, AnimationID.NPC_WARDENS_IDLE04, AnimationID.NPC_WARDENS_WALK04, null, null, VarrockStrayCatsConfig::appearanceWardenPetElidinis),
    APPEARANCEWARDENPETAKKHA(NpcID.WARDEN_PET_AKKHA, false, AnimationID.NPC_AKKHA_IDLE_SPEAR, AnimationID.NPC_AKKHA_WALK_03_SPEAR, null, null, VarrockStrayCatsConfig::appearanceWardenPetAkkha),
    APPEARANCEWARDENPETBABA(NpcID.WARDEN_PET_BABA, false, AnimationID.NPC_MANDRILL_IDLE, AnimationID.NPC_MANDRILL_WALK02, null, null, VarrockStrayCatsConfig::appearanceWardenPetBaba),
    APPEARANCEWARDENPETKEPHRI(NpcID.WARDEN_PET_KEPHRI, false, AnimationID.NPC_KEPHRI_IDLE, AnimationID.NPC_KEPHRI_WALK01, null, null, VarrockStrayCatsConfig::appearanceWardenPetKephri),
    APPEARANCEWARDENPETZEBAK(NpcID.WARDEN_PET_ZEBAK, false, AnimationID.CROC_READY, AnimationID.CROC_WALK, null, null, VarrockStrayCatsConfig::appearanceWardenPetZebak),
    APPEARANCEWARDENPETTUMEKENDESTROYED(NpcID.WARDEN_PET_TUMEKEN_DESTROYED, false, AnimationID.NPC_WARDENS_IDLE06, AnimationID.NPC_WARDENS_IDLE06, null, null, VarrockStrayCatsConfig::appearanceWardenPetTumekenDestroyed),
    APPEARANCEWARDENPETELIDINISDESTROYED(NpcID.WARDEN_PET_ELIDINIS_DESTROYED, false, AnimationID.NPC_WARDENS_IDLE06, AnimationID.NPC_WARDENS_IDLE06, null, null, VarrockStrayCatsConfig::appearanceWardenPetElidinisDestroyed),
    APPEARANCEVENENATISPETLEGACY(NpcID.VENENATISPET_LEGACY, false, AnimationID.SPIDER_UPDATE_READY, AnimationID.SPIDER_UPDATE_WALK, null, null, VarrockStrayCatsConfig::appearanceVenenatispetLegacy),
    APPEARANCECALLISTOPETLEGACY(NpcID.CALLISTOPET_LEGACY, false, AnimationID.BEAR_REWORK_READY, AnimationID.BEAR_REWORK_WALK, null, null, VarrockStrayCatsConfig::appearanceCallistopetLegacy),
    APPEARANCEVETIONPETLEGACY(NpcID.VETIONPET_LEGACY, false, AnimationID.SKELETON_UPDATE_GIANT_VARY3_READY, AnimationID.SKELETON_UPDATE_GIANT_WALK, null, null, VarrockStrayCatsConfig::appearanceVetionpetLegacy),
    APPEARANCEVETIONPET2LEGACY(NpcID.VETIONPET_2_LEGACY, false, AnimationID.SKELETON_UPDATE_GIANT_VARY3_READY, AnimationID.SKELETON_UPDATE_GIANT_WALK, null, null, VarrockStrayCatsConfig::appearanceVetionpet2Legacy),
    APPEARANCEMUSPAHPET(NpcID.MUSPAH_PET, false, AnimationID.NPC_MUSPAH_IDLE_01, AnimationID.NPC_MUSPAH_PET_WALK_FORWARD_01, null, null, VarrockStrayCatsConfig::appearanceMuspahPet),
    APPEARANCEMUSPAHPETMELEE(NpcID.MUSPAH_PET_MELEE, false, AnimationID.NPC_MUSPAH_IDLE_01, AnimationID.NPC_MUSPAH_PET_WALK_FORWARD_01, null, null, VarrockStrayCatsConfig::appearanceMuspahPetMelee),
    APPEARANCEMUSPAHPETSHIELDED(NpcID.MUSPAH_PET_SHIELDED, false, AnimationID.NPC_MUSPAH_IDLE_01, AnimationID.NPC_MUSPAH_PET_WALK_FORWARD_01, null, null, VarrockStrayCatsConfig::appearanceMuspahPetShielded),
    APPEARANCEWHISPERERPET(NpcID.WHISPERER_PET, false, AnimationID.NPC_WHISPERER_01_IDLE_01, AnimationID.NPC_WHISPERER_01_WALK_01_NOSOUND, null, null, VarrockStrayCatsConfig::appearanceWhispererPet),
    APPEARANCEVARDORVISPET(NpcID.VARDORVIS_PET, false, AnimationID.NPC_VARDORVIS_01_IDLE_01, AnimationID.NPC_VARDORVIS_01_WALK_FORWARD_01_NO_SOUND, null, null, VarrockStrayCatsConfig::appearanceVardorvisPet),
    APPEARANCEDUKESUCELLUSPET(NpcID.DUKE_SUCELLUS_PET, false, AnimationID.DUKE_SUCELLUS_PET_01_IDLE_01, AnimationID.DUKE_SUCELLUS_PET_01_WALK_01, null, null, VarrockStrayCatsConfig::appearanceDukeSucellusPet),
    APPEARANCELEVIATHANPET(NpcID.LEVIATHAN_PET, false, AnimationID.NPC_LEVIATHAN_01_IDLE_02, AnimationID.NPC_LEVIATHAN_01_PETWALK, null, null, VarrockStrayCatsConfig::appearanceLeviathanPet),
    APPEARANCESKILLPETWC(NpcID.SKILLPETWC, false, AnimationID.LORE_BEAVER_READY, AnimationID.LORE_BEAVER_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetwc),
    APPEARANCESKILLPETWCOAK(NpcID.SKILLPET_WC_OAK, false, AnimationID.LORE_BEAVER_READY, AnimationID.LORE_BEAVER_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetWcOak),
    APPEARANCESKILLPETWCWILLOW(NpcID.SKILLPET_WC_WILLOW, false, AnimationID.LORE_BEAVER_READY, AnimationID.LORE_BEAVER_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetWcWillow),
    APPEARANCESKILLPETWCMAPLE(NpcID.SKILLPET_WC_MAPLE, false, AnimationID.LORE_BEAVER_READY, AnimationID.LORE_BEAVER_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetWcMaple),
    APPEARANCESKILLPETWCYEW(NpcID.SKILLPET_WC_YEW, false, AnimationID.LORE_BEAVER_READY, AnimationID.LORE_BEAVER_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetWcYew),
    APPEARANCESKILLPETWCMAGIC(NpcID.SKILLPET_WC_MAGIC, false, AnimationID.LORE_BEAVER_READY, AnimationID.LORE_BEAVER_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetWcMagic),
    APPEARANCESKILLPETWCREDWOOD(NpcID.SKILLPET_WC_REDWOOD, false, AnimationID.LORE_BEAVER_READY, AnimationID.LORE_BEAVER_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetWcRedwood),
    APPEARANCESKILLPETWCTEAK(NpcID.SKILLPET_WC_TEAK, false, AnimationID.LORE_BEAVER_READY, AnimationID.LORE_BEAVER_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetWcTeak),
    APPEARANCESKILLPETWCMAHOGANY(NpcID.SKILLPET_WC_MAHOGANY, false, AnimationID.LORE_BEAVER_READY, AnimationID.LORE_BEAVER_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetWcMahogany),
    APPEARANCESKILLPETWCARCTIC(NpcID.SKILLPET_WC_ARCTIC, false, AnimationID.LORE_BEAVER_READY, AnimationID.LORE_BEAVER_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetWcArctic),
    APPEARANCESKILLPETWCPHEASANT(NpcID.SKILLPET_WC_PHEASANT, false, AnimationID.PHEASENT_READY, AnimationID.PHEASENT_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetWcPheasant),
    APPEARANCESKILLPETWCFOX(NpcID.SKILLPET_WC_FOX, false, AnimationID.DOG_UPDATE_SMALL_DOG_READY, AnimationID.DOG_UPDATE_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetWcFox),
    APPEARANCERTBRANDAPET(NpcID.RTBRANDA_PET, false, AnimationID.FIRE_GIANT_BRANDA_QUEEN_IDLE01, AnimationID.FIRE_GIANT_BRANDA_QUEEN_WALK01, null, null, VarrockStrayCatsConfig::appearanceRtbrandaPet),
    APPEARANCERTELDRICPET(NpcID.RTELDRIC_PET, false, AnimationID.ICE_GIANT_ELDRIC_KING_IDLE01, AnimationID.ICE_GIANT_ELDRIC_KING_WALK01, null, null, VarrockStrayCatsConfig::appearanceRteldricPet),
    APPEARANCESOLHEREDITPET(NpcID.SOLHEREDIT_PET, false, AnimationID.NPC_COLOSSI_FINALBOSS_01_IDLE, AnimationID.NPC_COLOSSI_SHOCKWAVE_01_WALK_NOSOUND, null, null, VarrockStrayCatsConfig::appearanceSolhereditPet),
    APPEARANCEQUETZALPET(NpcID.QUETZAL_PET, false, AnimationID.NPC_QUETZAL_FLYING_IDLE_PET_01, AnimationID.NPC_QUETZAL_FLYING_IDLE_PET_01, null, null, VarrockStrayCatsConfig::appearanceQuetzalPet),
    APPEARANCEWGSBROAV(NpcID.WGS_BROAV, false, AnimationID.WGS_BROAV_READY_AND_EXTRA, AnimationID.WGS_BROAV_WALK, null, null, VarrockStrayCatsConfig::appearanceWgsBroav),
    APPEARANCEARAXXORPET(NpcID.ARAXXOR_PET, false, AnimationID.NPC_ARAXXOR_01_IDLE_01, AnimationID.NPC_ARAXXOR_01_WALK_01, null, null, VarrockStrayCatsConfig::appearanceAraxxorPet),
    APPEARANCEARAXXORPETCUTE(NpcID.ARAXXOR_PET_CUTE, false, AnimationID.SOTE_GAUNTLET_SPIDER_IDLE, AnimationID.NPC_ARAXYTE01_WALK_FAST, null, null, VarrockStrayCatsConfig::appearanceAraxxorPetCute),
    APPEARANCESKILLPETAGILITYBONE(NpcID.SKILLPET_AGILITY_BONE, false, AnimationID.BONE_SQUIRREL_IDLE, AnimationID.BONE_SQUIRREL_HOP, null, null, VarrockStrayCatsConfig::appearanceSkillpetAgilityBone),
    APPEARANCEHUEYPET(NpcID.HUEY_PET, false, AnimationID.NPC_HUEYCOATL_PET_IDLE_01, AnimationID.NPC_HUEYCOATL_PET_WALK_01, null, null, VarrockStrayCatsConfig::appearanceHueyPet),
    APPEARANCEAMOXLIATLPET(NpcID.AMOXLIATL_PET, false, AnimationID.AMOXLIATL_IDLE, AnimationID.AMOXLIATL_WALK, null, null, VarrockStrayCatsConfig::appearanceAmoxliatlPet),
    APPEARANCEYAMAPET(NpcID.YAMA_PET, false, AnimationID.NPC_YAMA01_IDLE01, AnimationID.NPC_YAMA01_WALK03, null, null, VarrockStrayCatsConfig::appearanceYamaPet),
    APPEARANCEDOMPET(NpcID.DOM_PET, false, AnimationID.NPC_DOOM_BOSS_PET_IDLE, AnimationID.NPC_DOOM_BOSS_PET_WALK, null, null, VarrockStrayCatsConfig::appearanceDomPet),
    APPEARANCESKILLPETMININGLEAD(NpcID.SKILLPET_MINING_LEAD, false, AnimationID.ROCK_GOLEM_IDLE, AnimationID.ROCK_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetMiningLead),
    APPEARANCESKILLPETMININGRUBIUM(NpcID.SKILLPET_MINING_RUBIUM, false, AnimationID.ROCK_GOLEM_IDLE, AnimationID.ROCK_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetMiningRubium),
    APPEARANCESKILLPETMININGNICKEL(NpcID.SKILLPET_MINING_NICKEL, false, AnimationID.ROCK_GOLEM_IDLE, AnimationID.ROCK_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetMiningNickel),
    APPEARANCESKILLPETWCCAMPHOR(NpcID.SKILLPET_WC_CAMPHOR, false, AnimationID.LORE_BEAVER_READY, AnimationID.LORE_BEAVER_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetWcCamphor),
    APPEARANCESKILLPETWCIRONWOOD(NpcID.SKILLPET_WC_IRONWOOD, false, AnimationID.LORE_BEAVER_READY, AnimationID.LORE_BEAVER_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetWcIronwood),
    APPEARANCESKILLPETWCJATOBA(NpcID.SKILLPET_WC_JATOBA, false, AnimationID.LORE_BEAVER_READY, AnimationID.LORE_BEAVER_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetWcJatoba),
    APPEARANCESKILLPETWCROSEWOOD(NpcID.SKILLPET_WC_ROSEWOOD, false, AnimationID.LORE_BEAVER_READY, AnimationID.LORE_BEAVER_WALK, null, null, VarrockStrayCatsConfig::appearanceSkillpetWcRosewood),
    APPEARANCESKILLPETSAILING(NpcID.SKILLPET_SAILING, false, AnimationID.TURTLE_IDLE01, AnimationID.TURTLE_WALK01, null, null, VarrockStrayCatsConfig::appearanceSkillpetSailing),
    APPEARANCEGRYPHONBOSSPET(NpcID.GRYPHONBOSS_PET, false, AnimationID.NPC_GRYPHON_PET_IDLE01, AnimationID.NPC_GRYPHON_PET_WALK01, null, null, VarrockStrayCatsConfig::appearanceGryphonbossPet),
    APPEARANCEGRYPHONBOSSPETADULT(NpcID.GRYPHONBOSS_PET_ADULT, false, AnimationID.GRYPHON_BOSS_IDLE01, AnimationID.GRYPHON_BOSS_WALK01, null, null, VarrockStrayCatsConfig::appearanceGryphonbossPetAdult),
    APPEARANCECOWBOSSPET(NpcID.COWBOSS_PET, false, AnimationID.COW_JUST_READY_UPDATE, AnimationID.CALF_UPDATE_WALK, null, null, VarrockStrayCatsConfig::appearanceCowbossPet),
    APPEARANCEMAGGOTKINGPET(NpcID.MAGGOT_KING_PET, false, AnimationID.NPC_MAGGOT_KING_IDLE_01, AnimationID.NPC_MAGGOT_KING_PET_WALK_FORWARD_01, null, null, VarrockStrayCatsConfig::appearanceMaggotKingPet),
    APPEARANCEGOATPITPET(NpcID.GOAT_PIT_PET, false, AnimationID.GOAT_UPDATE_READY, AnimationID.GOAT_UPDATE_WALK_MERGE, null, null, VarrockStrayCatsConfig::appearanceGoatPitPet),
    APPEARANCEMADANGELPET(NpcID.MAD_ANGEL_PET, false, AnimationID.NPC_MAD_ANGEL_IDLE, AnimationID.NPC_MAD_ANGEL_IDLE, null, null, VarrockStrayCatsConfig::appearanceMadAngelPet),
    APPEARANCEDAGANNOTHDUNGEONPRESSUREPETEGG(NpcID.DAGANNOTH_DUNGEON_PRESSURE_PET_EGG, false, -1, -1, null, null, VarrockStrayCatsConfig::appearanceDagannothDungeonPressurePetEgg),
    APPEARANCEDAGANNOTHDUNGEONPRESSUREPETEASTER26EGG(NpcID.DAGANNOTH_DUNGEON_PRESSURE_PET_EASTER26_EGG, false, -1, -1, null, null, VarrockStrayCatsConfig::appearanceDagannothDungeonPressurePetEaster26Egg),
    APPEARANCEDAGANNOTHDUNGEONPRESSUREPETEASTER26EGG02(NpcID.DAGANNOTH_DUNGEON_PRESSURE_PET_EASTER26_EGG_02, false, -1, -1, null, null, VarrockStrayCatsConfig::appearanceDagannothDungeonPressurePetEaster26Egg02),
    APPEARANCEDAGANNOTHDUNGEONPRESSUREPETEASTER26EGG03(NpcID.DAGANNOTH_DUNGEON_PRESSURE_PET_EASTER26_EGG_03, false, -1, -1, null, null, VarrockStrayCatsConfig::appearanceDagannothDungeonPressurePetEaster26Egg03),
    APPEARANCEDAGANNOTHDUNGEONPRESSUREPETEASTER26EGG04(NpcID.DAGANNOTH_DUNGEON_PRESSURE_PET_EASTER26_EGG_04, false, -1, -1, null, null, VarrockStrayCatsConfig::appearanceDagannothDungeonPressurePetEaster26Egg04),
    APPEARANCEDAGANNOTHDUNGEONPRESSUREPETEASTER26EGG05(NpcID.DAGANNOTH_DUNGEON_PRESSURE_PET_EASTER26_EGG_05, false, -1, -1, null, null, VarrockStrayCatsConfig::appearanceDagannothDungeonPressurePetEaster26Egg05),
    APPEARANCEDAGANNOTHDUNGEONPRESSUREPETEASTER26EGG06(NpcID.DAGANNOTH_DUNGEON_PRESSURE_PET_EASTER26_EGG_06, false, -1, -1, null, null, VarrockStrayCatsConfig::appearanceDagannothDungeonPressurePetEaster26Egg06),
    APPEARANCEDAGANNOTHDUNGEONPRESSUREPETEASTER26EGG07(NpcID.DAGANNOTH_DUNGEON_PRESSURE_PET_EASTER26_EGG_07, false, -1, -1, null, null, VarrockStrayCatsConfig::appearanceDagannothDungeonPressurePetEaster26Egg07),
    APPEARANCEPOHHWCHAIR(NpcID.POH_HW_CHAIR, false, -1, AnimationID.DRAYNOR_POSSESED_CHAIR, null, null, VarrockStrayCatsConfig::appearancePohHwChair),
    APPEARANCEPOHFISHBOWLMAYOROFCATHERBY(NpcID.POH_FISHBOWL_MAYOR_OF_CATHERBY, false, -1, -1, null, null, VarrockStrayCatsConfig::appearancePohFishbowlMayorOfCatherby),
    APPEARANCEBARROWSAHRIM(NpcID.BARROWS_AHRIM, false, AnimationID.HUMAN_STAFFREADY, AnimationID.HUMAN_HALBERDWALK_F, null, null, VarrockStrayCatsConfig::appearanceBarrowsAhrim),
    APPEARANCEBARROWSKARIL(NpcID.BARROWS_KARIL, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceBarrowsKaril),
    APPEARANCEBARROWSDHAROK(NpcID.BARROWS_DHAROK, false, AnimationID.BARROW_DHAROK_READY, AnimationID.BARROW_DHAROK_WALK, null, null, VarrockStrayCatsConfig::appearanceBarrowsDharok),
    APPEARANCEBARROWSGUTHAN(NpcID.BARROWS_GUTHAN, false, AnimationID.HUMAN_STAFFREADY, AnimationID.HUMAN_HALBERDWALK_F, null, null, VarrockStrayCatsConfig::appearanceBarrowsGuthan),
    APPEARANCEBARROWSTORAG(NpcID.BARROWS_TORAG, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceBarrowsTorag),
    APPEARANCEBARROWSVERAC(NpcID.BARROWS_VERAC, false, AnimationID.BARROW_GUTHAN_READY, AnimationID.BARROW_GUTHAN_WALK, null, null, VarrockStrayCatsConfig::appearanceBarrowsVerac),
    APPEARANCEGEMSTONECRAB(NpcID.GEMSTONE_CRAB, false, AnimationID.CRAB_BOSS_IDLE, -1, null, null, VarrockStrayCatsConfig::appearanceGemstoneCrab),
    APPEARANCERATBOSSNORMAL(NpcID.RAT_BOSS_NORMAL, false, AnimationID.NPC_RAT_BOSS_IDLE_01, AnimationID.NPC_RAT_BOSS_WALK_01, null, null, VarrockStrayCatsConfig::appearanceRatBossNormal),
    APPEARANCEMOLEGIANT(NpcID.MOLE_GIANT, false, AnimationID.MOLE_READY, AnimationID.MOLE_WALK, null, null, VarrockStrayCatsConfig::appearanceMoleGiant),
    APPEARANCEFOSSILCRAZYARCHAEOLOGIST(NpcID.FOSSIL_CRAZY_ARCHAEOLOGIST, false, AnimationID.BOOK_CHUCK_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceFossilCrazyArchaeologist),
    APPEARANCEDAGCAVERANGEDBOSS(NpcID.DAGCAVE_RANGED_BOSS, false, AnimationID.DAGANNOTH_MEGANOTH_READY, AnimationID.DAGANNOTH_MEGANOTH_WALK, null, null, VarrockStrayCatsConfig::appearanceDagcaveRangedBoss),
    APPEARANCEDAGCAVEMELEEBOSS(NpcID.DAGCAVE_MELEE_BOSS, false, AnimationID.DAGANNOTH_MEGANOTH_READY, AnimationID.DAGANNOTH_MEGANOTH_WALK, null, null, VarrockStrayCatsConfig::appearanceDagcaveMeleeBoss),
    APPEARANCEDAGCAVEMAGICBOSS(NpcID.DAGCAVE_MAGIC_BOSS, false, AnimationID.DAGANNOTH_MEGANOTH_READY, AnimationID.DAGANNOTH_MEGANOTH_WALK, null, null, VarrockStrayCatsConfig::appearanceDagcaveMagicBoss),
    APPEARANCESARACHNIS(NpcID.SARACHNIS, false, AnimationID.HOSDUN_SPIDER_BOSS_IDLE, AnimationID.HODSUN_SPIDER_BOSS_WALK, null, null, VarrockStrayCatsConfig::appearanceSarachnis),
    APPEARANCEPMOONBOSSBLOODMOONVIS(NpcID.PMOON_BOSS_BLOOD_MOON_VIS, false, -1, -1, null, null, VarrockStrayCatsConfig::appearancePmoonBossBloodMoonVis),
    APPEARANCEPMOONBOSSBLUEMOONVIS(NpcID.PMOON_BOSS_BLUE_MOON_VIS, false, -1, -1, null, null, VarrockStrayCatsConfig::appearancePmoonBossBlueMoonVis),
    APPEARANCEPMOONBOSSECLIPSEMOONVIS(NpcID.PMOON_BOSS_ECLIPSE_MOON_VIS, false, -1, -1, null, null, VarrockStrayCatsConfig::appearancePmoonBossEclipseMoonVis),
    APPEARANCEKALPHITEQUEEN(NpcID.KALPHITE_QUEEN, false, AnimationID.KALPHITE_UPDATE_QUEEN_READY, AnimationID.KALPHITE_UPDATE_QUEEN_WALK, null, null, VarrockStrayCatsConfig::appearanceKalphiteQueen),
    APPEARANCEGODWARSARMADYLAVATAR(NpcID.GODWARS_ARMADYL_AVATAR, false, AnimationID.GODWARS_ARMADYL_AVATAR_READY, AnimationID.GODWARS_ARMADYL_AVATAR_WALK, null, null, VarrockStrayCatsConfig::appearanceGodwarsArmadylAvatar),
    APPEARANCEGODWARSSARADOMINAVATAR(NpcID.GODWARS_SARADOMIN_AVATAR, false, AnimationID.GODWARS_SARADOMIN_READY, AnimationID.GODWARS_SARADOMIN_WALK, null, null, VarrockStrayCatsConfig::appearanceGodwarsSaradominAvatar),
    APPEARANCEGODWARSBANDOSAVATAR(NpcID.GODWARS_BANDOS_AVATAR, false, AnimationID.GODWARS_BANDOS_READY, AnimationID.GODWARS_BANDOS_WALK, null, null, VarrockStrayCatsConfig::appearanceGodwarsBandosAvatar),
    APPEARANCEGODWARSZAMORAKAVATAR(NpcID.GODWARS_ZAMORAK_AVATAR, false, AnimationID.GODWARS_ZAMORAK_READY, AnimationID.GODWARS_ZAMORAK_WALK, null, null, VarrockStrayCatsConfig::appearanceGodwarsZamorakAvatar),
    APPEARANCEHUEYHEAD(NpcID.HUEY_HEAD, false, AnimationID.HUEY_IDLE, -1, null, null, VarrockStrayCatsConfig::appearanceHueyHead),
    APPEARANCECORPBEAST(NpcID.CORP_BEAST, false, AnimationID.CORPBEAST_IDLE, AnimationID.CORPBEAST_WALKING, null, null, VarrockStrayCatsConfig::appearanceCorpBeast),
    APPEARANCENEX(NpcID.NEX, false, AnimationID.NEX_READY, AnimationID.NEX_RUN, null, null, VarrockStrayCatsConfig::appearanceNex),
    APPEARANCECHAOSFANATIC(NpcID.CHAOS_FANATIC, false, AnimationID.DRUNK_PLAYER_READY, AnimationID.DRUNK_PLAYER_WALK, null, null, VarrockStrayCatsConfig::appearanceChaosFanatic),
    APPEARANCECRAZYARCHAEOLOGIST(NpcID.CRAZY_ARCHAEOLOGIST, false, AnimationID.BOOK_CHUCK_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceCrazyArchaeologist),
    APPEARANCESCORPIA(NpcID.SCORPIA, false, AnimationID.SCORPION_UPDATE_READY, AnimationID.SCORPION_UPDATE_FIGHT_ARENA_WALK, null, null, VarrockStrayCatsConfig::appearanceScorpia),
    APPEARANCEKINGDRAGON(NpcID.KING_DRAGON, false, AnimationID.DRAGON_READY, AnimationID.DRAGON_WALK_KBD, null, null, VarrockStrayCatsConfig::appearanceKingDragon),
    APPEARANCECHAOSELEMENTAL(NpcID.CHAOSELEMENTAL, false, AnimationID.CHAOSELEMENTAL_READY, AnimationID.CHAOSELEMENTAL_WALK, null, null, VarrockStrayCatsConfig::appearanceChaoselemental),
    APPEARANCEWILDCAVESUPERIOR(NpcID.WILD_CAVE_SUPERIOR, false, AnimationID.NPC_REVENANT_SUPERIOR_IDLE, AnimationID.NPC_REVENANT_SUPERIOR_WALK, null, null, VarrockStrayCatsConfig::appearanceWildCaveSuperior),
    APPEARANCEVETIONSINGLE(NpcID.VETION_SINGLE, false, AnimationID.NPC_VETION_IDLE_01, AnimationID.NPC_VETION_WALK_01, null, null, VarrockStrayCatsConfig::appearanceVetionSingle),
    APPEARANCEVETION(NpcID.VETION, false, AnimationID.NPC_VETION_IDLE_01, AnimationID.NPC_VETION_WALK_01, null, null, VarrockStrayCatsConfig::appearanceVetion),
    APPEARANCEVENENATISSINGLES(NpcID.VENENATIS_SINGLES, false, AnimationID.NPC_VENENATIS_IDLE_01, AnimationID.NPC_VENENATIS_RUN_01, null, null, VarrockStrayCatsConfig::appearanceVenenatisSingles),
    APPEARANCEVENENATIS(NpcID.VENENATIS, false, AnimationID.NPC_VENENATIS_IDLE_01, AnimationID.NPC_VENENATIS_RUN_01, null, null, VarrockStrayCatsConfig::appearanceVenenatis),
    APPEARANCECALLISTOSINGLES(NpcID.CALLISTO_SINGLES, false, AnimationID.NPC_CALLISTO_IDLE01, AnimationID.NPC_CALLISTO_WALK01, null, null, VarrockStrayCatsConfig::appearanceCallistoSingles),
    APPEARANCECALLISTO(NpcID.CALLISTO, false, AnimationID.NPC_CALLISTO_IDLE01, AnimationID.NPC_CALLISTO_WALK01, null, null, VarrockStrayCatsConfig::appearanceCallisto),
    APPEARANCECOWBOSS(NpcID.COWBOSS, false, AnimationID.COW_BOSS_IDLE, AnimationID.COW_BOSS_WALK, null, null, VarrockStrayCatsConfig::appearanceCowboss),
    APPEARANCECOWBOSSHARDMODE(NpcID.COWBOSS_HARDMODE, false, AnimationID.COW_BOSS_IDLE, AnimationID.COW_BOSS_WALK, null, null, VarrockStrayCatsConfig::appearanceCowbossHardmode),
    APPEARANCEHILLGIANTBOSS(NpcID.HILLGIANT_BOSS, false, AnimationID.GIANT_UPDATE_BASIC_READY, AnimationID.GIANT_UPDATE_BASIC_WALK, null, null, VarrockStrayCatsConfig::appearanceHillgiantBoss),
    APPEARANCEGBMOSSGIANT(NpcID.GB_MOSSGIANT, false, AnimationID.GIANT_UPDATE_MOSS_READY, AnimationID.GIANT_UPDATE_MOSS_WALK, null, null, VarrockStrayCatsConfig::appearanceGbMossgiant),
    APPEARANCEAMOXLIATL(NpcID.AMOXLIATL, false, AnimationID.AMOXLIATL_IDLE, AnimationID.AMOXLIATL_WALK, null, null, VarrockStrayCatsConfig::appearanceAmoxliatl),
    APPEARANCERTFIREQUEEN(NpcID.RT_FIRE_QUEEN, false, AnimationID.FIRE_GIANT_BRANDA_QUEEN_IDLE01, AnimationID.FIRE_GIANT_BRANDA_QUEEN_WALK01, null, null, VarrockStrayCatsConfig::appearanceRtFireQueen),
    APPEARANCEDOMBOSS(NpcID.DOM_BOSS, false, AnimationID.DOM_IDLE, -1, null, null, VarrockStrayCatsConfig::appearanceDomBoss),
    APPEARANCEMADANGEL(NpcID.MAD_ANGEL, false, AnimationID.NPC_MAD_ANGEL_IDLE, AnimationID.NPC_MAD_ANGEL_IDLE, null, null, VarrockStrayCatsConfig::appearanceMadAngel),
    APPEARANCESNAKEBOSSBOSSRANGED(NpcID.SNAKEBOSS_BOSS_RANGED, false, AnimationID.SNAKEBOSS_IDLE, AnimationID.SNAKEBOSS_IDLE, null, null, VarrockStrayCatsConfig::appearanceSnakebossBossRanged),
    APPEARANCEVORKATHQUEST(NpcID.VORKATH_QUEST, false, AnimationID.DS2_VORKATH_IDLE, AnimationID.DS2_VORKATH_WALK, null, null, VarrockStrayCatsConfig::appearanceVorkathQuest),
    APPEARANCEMUSPAH(NpcID.MUSPAH, false, AnimationID.NPC_MUSPAH_IDLE_01, AnimationID.NPC_MUSPAH_WALK_FORWARD_01, null, null, VarrockStrayCatsConfig::appearanceMuspah),
    APPEARANCEMAGGOTKING(NpcID.MAGGOT_KING, false, AnimationID.NPC_MAGGOT_KING_IDLE_01, AnimationID.NPC_MAGGOT_KING_WALK_FORWARD_01, null, null, VarrockStrayCatsConfig::appearanceMaggotKing),
    APPEARANCENIGHTMAREPHASE01(NpcID.NIGHTMARE_PHASE_01, false, AnimationID.NIGHTMARE_IDLE, AnimationID.NIGHTMARE_WALK, null, null, VarrockStrayCatsConfig::appearanceNightmarePhase01),
    APPEARANCENIGHTMARECHALLENGEPHASE01(NpcID.NIGHTMARE_CHALLENGE_PHASE_01, false, AnimationID.NIGHTMARE_IDLE, AnimationID.NIGHTMARE_WALK, null, null, VarrockStrayCatsConfig::appearanceNightmareChallengePhase01),
    APPEARANCEYAMA(NpcID.YAMA, false, AnimationID.NPC_YAMA01_IDLE01, AnimationID.NPC_YAMA01_WALK01, null, null, VarrockStrayCatsConfig::appearanceYama),
    APPEARANCEDUKESUCELLUSASLEEP(NpcID.DUKE_SUCELLUS_ASLEEP, false, AnimationID.NPC_DUKE_SUCELLUS01_IDLE_SLEEP_01, -1, null, null, VarrockStrayCatsConfig::appearanceDukeSucellusAsleep),
    APPEARANCELEVIATHAN(NpcID.LEVIATHAN, false, AnimationID.NPC_LEVIATHAN_01_IDLE_01, AnimationID.NPC_LEVIATHAN_01_IDLE_01, null, null, VarrockStrayCatsConfig::appearanceLeviathan),
    APPEARANCEWHISPERER(NpcID.WHISPERER, false, AnimationID.NPC_WHISPERER_01_IDLE_01, AnimationID.NPC_WHISPERER_01_WALK_01, null, null, VarrockStrayCatsConfig::appearanceWhisperer),
    APPEARANCEVARDORVIS(NpcID.VARDORVIS, false, AnimationID.NPC_VARDORVIS_01_IDLE_01, AnimationID.NPC_VARDORVIS_01_WALK_FORWARD_01, null, null, VarrockStrayCatsConfig::appearanceVardorvis),
    APPEARANCETRAILMIMICCOMBAT(NpcID.TRAIL_MIMIC_COMBAT, false, AnimationID.MIMIC_READY, AnimationID.MIMIC_WALK, null, null, VarrockStrayCatsConfig::appearanceTrailMimicCombat),
    APPEARANCEHESPORI(NpcID.HESPORI, false, AnimationID.HESPORI_READY, AnimationID.HESPORI_READY, null, null, VarrockStrayCatsConfig::appearanceHespori),
    APPEARANCECATABOSS(NpcID.CATA_BOSS, false, AnimationID.DEMON_UPDATE_READY, AnimationID.DEMON_UPDATE_WALK, null, null, VarrockStrayCatsConfig::appearanceCataBoss),
    APPEARANCEGRYPHONBOSS(NpcID.GRYPHON_BOSS, false, AnimationID.GRYPHON_BOSS_IDLE01, AnimationID.GRYPHON_BOSS_WALK01, null, null, VarrockStrayCatsConfig::appearanceGryphonBoss),
    APPEARANCEGARGBOSSDUSKPHASE1DEFENSIVE(NpcID.GARGBOSS_DUSK_PHASE1_DEFENSIVE, false, AnimationID.GG_DUSK_IDLE_DEFENSIVE, AnimationID.GG_DUSK_WALK_DEFENSIVE, null, null, VarrockStrayCatsConfig::appearanceGargbossDuskPhase1Defensive),
    APPEARANCEABYSSALSIRESIREPUPPET(NpcID.ABYSSALSIRE_SIRE_PUPPET, false, AnimationID.SIRE_IDLE_TWO, AnimationID.SIRE_WALK, null, null, VarrockStrayCatsConfig::appearanceAbyssalsireSirePuppet),
    APPEARANCESLAYERKRAKENBOSS(NpcID.SLAYER_KRAKEN_BOSS, false, AnimationID.SWAN_QUEEN_READY, AnimationID.SWAN_QUEEN_READY, null, null, VarrockStrayCatsConfig::appearanceSlayerKrakenBoss),
    APPEARANCECERBERUSATTACKING(NpcID.CERBERUS_ATTACKING, false, AnimationID.CERBERUS_IDLE, AnimationID.CERBERUS_WALK, null, null, VarrockStrayCatsConfig::appearanceCerberusAttacking),
    APPEARANCEARAXXOR(NpcID.ARAXXOR, false, AnimationID.NPC_ARAXXOR_01_IDLE_01, AnimationID.NPC_ARAXXOR_01_WALK_01, null, null, VarrockStrayCatsConfig::appearanceAraxxor),
    APPEARANCESMOKEDEVILBOSS(NpcID.SMOKE_DEVIL_BOSS, false, AnimationID.LORE_DUST_DEVIL_READY, AnimationID.LORE_DUST_DEVIL_WALK, null, null, VarrockStrayCatsConfig::appearanceSmokeDevilBoss),
    APPEARANCEHYDRABOSS(NpcID.HYDRABOSS, false, AnimationID.HYDRA_STAGE_1_READY, AnimationID.HYDRA_STAGE_1_WALK, null, null, VarrockStrayCatsConfig::appearanceHydraboss),
    APPEARANCECRYSTALHUNLLEFMELEE(NpcID.CRYSTAL_HUNLLEF_MELEE, false, AnimationID.HUNLLEF_READY, AnimationID.HUNLLEF_WALK, null, null, VarrockStrayCatsConfig::appearanceCrystalHunllefMelee),
    APPEARANCECRYSTALHUNLLEFMELEEHM(NpcID.CRYSTAL_HUNLLEF_MELEE_HM, false, AnimationID.HUNLLEF_READY, AnimationID.HUNLLEF_WALK, null, null, VarrockStrayCatsConfig::appearanceCrystalHunllefMeleeHm),
    APPEARANCETZHAARFIGHTCAVESWARMBOSS(NpcID.TZHAAR_FIGHTCAVE_SWARM_BOSS, false, AnimationID.LORDMAGMUS_READY, AnimationID.LORDMAGMUS_WALK, null, null, VarrockStrayCatsConfig::appearanceTzhaarFightcaveSwarmBoss),
    APPEARANCEINFERNOTZKALZUKPLACEHOLDER(NpcID.INFERNO_TZKALZUK_PLACEHOLDER, false, AnimationID.ZUK_IDLE, -1, null, null, VarrockStrayCatsConfig::appearanceInfernoTzkalzukPlaceholder),
    APPEARANCECOLOSSEUMSOLP1(NpcID.COLOSSEUM_SOL_P1, false, AnimationID.NPC_COLOSSI_FINALBOSS_01_IDLE, AnimationID.NPC_COLOSSI_FINALBOSS_01_WALK, null, null, VarrockStrayCatsConfig::appearanceColosseumSolP1),
    APPEARANCETEMPOROSSBOSSREADY(NpcID.TEMPOROSS_BOSS_READY, false, AnimationID.FSB_READY, -1, null, null, VarrockStrayCatsConfig::appearanceTemporossBossReady),
    APPEARANCEZALCANO(NpcID.ZALCANO, false, AnimationID.ZALCANO_IDLE, AnimationID.ZALCANO_WALK, null, null, VarrockStrayCatsConfig::appearanceZalcano),
    APPEARANCERAIDSTEKTONWAITING(NpcID.RAIDS_TEKTON_WAITING, false, AnimationID.TEKTON_SPAWN, AnimationID.TEKTON_SPAWN, null, null, VarrockStrayCatsConfig::appearanceRaidsTektonWaiting),
    APPEARANCERAIDSVANGUARDWALKING(NpcID.RAIDS_VANGUARD_WALKING, false, AnimationID.VANGUARD_IDLE_BASIC, AnimationID.VANGUARD_WALK, null, null, VarrockStrayCatsConfig::appearanceRaidsVanguardWalking),
    APPEARANCERAIDSVESPULAFLYING(NpcID.RAIDS_VESPULA_FLYING, false, AnimationID.VESPULA_FLYING, AnimationID.VESPULA_FLYING, null, null, VarrockStrayCatsConfig::appearanceRaidsVespulaFlying),
    APPEARANCERAIDSVASANISTIRIOWALKING(NpcID.RAIDS_VASANISTIRIO_WALKING, false, AnimationID.VASA_IDLE, AnimationID.VASA_WALK, null, null, VarrockStrayCatsConfig::appearanceRaidsVasanistirioWalking),
    APPEARANCERAIDSDOGODILEJUNIOR(NpcID.RAIDS_DOGODILE_JUNIOR, false, AnimationID.DOHGADYLE_IDLE, AnimationID.DOHGADYLE_WALK, null, null, VarrockStrayCatsConfig::appearanceRaidsDogodileJunior),
    APPEARANCEOLMHEAD(NpcID.OLM_HEAD, false, AnimationID.OLM_HEAD_IDLE_FRONT, -1, null, null, VarrockStrayCatsConfig::appearanceOlmHead),
    APPEARANCETOBMAIDEN100(NpcID.TOB_MAIDEN_100, false, AnimationID.MAIDEN_IDLE, AnimationID.MAIDEN_IDLE, null, null, VarrockStrayCatsConfig::appearanceTobMaiden100),
    APPEARANCETOBBLOAT(NpcID.TOB_BLOAT, false, AnimationID.TOB_BLOAT_READY, AnimationID.TOB_BLOAT_WALK, null, null, VarrockStrayCatsConfig::appearanceTobBloat),
    APPEARANCENYLOCASBOSSMELEE(NpcID.NYLOCAS_BOSS_MELEE, false, AnimationID.TOP_SPIDER_MELEE_IDLE, AnimationID.TOP_SPIDER_MELEE_WALK, null, null, VarrockStrayCatsConfig::appearanceNylocasBossMelee),
    APPEARANCETOBSOTETSEGCOMBAT(NpcID.TOB_SOTETSEG_COMBAT, false, AnimationID.TOB_SOTETSEG_IDLE, AnimationID.TOB_SOTETSEG_WALK, null, null, VarrockStrayCatsConfig::appearanceTobSotetsegCombat),
    APPEARANCETOBXARPUSSTATIC(NpcID.TOB_XARPUS_STATIC, false, AnimationID.TOB_XARPUS_ABSORB, AnimationID.TOB_XARPUS_ABSORB, null, null, VarrockStrayCatsConfig::appearanceTobXarpusStatic),
    APPEARANCEVERZIKPHASE2(NpcID.VERZIK_PHASE2, false, AnimationID.VERZIK_PHASE2_IDLE, AnimationID.VERZIK_PHASE2_IDLE, null, null, VarrockStrayCatsConfig::appearanceVerzikPhase2),
    APPEARANCEAKKHAMELEE(NpcID.AKKHA_MELEE, false, AnimationID.NPC_AKKHA_IDLE_SPEAR, AnimationID.NPC_AKKHA_WALK_02_SPEAR, null, null, VarrockStrayCatsConfig::appearanceAkkhaMelee),
    APPEARANCETOABABA(NpcID.TOA_BABA, false, AnimationID.NPC_MANDRILL_IDLE, AnimationID.NPC_MANDRILL_WALK01, null, null, VarrockStrayCatsConfig::appearanceToaBaba),
    APPEARANCETOAKEPHRIBOSSSHIELDED(NpcID.TOA_KEPHRI_BOSS_SHIELDED, false, AnimationID.NPC_KEPHRI_IDLE, AnimationID.NPC_KEPHRI_IDLE, null, null, VarrockStrayCatsConfig::appearanceToaKephriBossShielded),
    APPEARANCETOAZEBAK(NpcID.TOA_ZEBAK, false, AnimationID.NPC_ZEBAK01_IDLE, -1, null, null, VarrockStrayCatsConfig::appearanceToaZebak),
    APPEARANCETOAWARDENTUMEKENPHASE1(NpcID.TOA_WARDEN_TUMEKEN_PHASE1, false, AnimationID.NPC_WARDENS_DORMANT01, AnimationID.NPC_WARDENS_WALK01, null, null, VarrockStrayCatsConfig::appearanceToaWardenTumekenPhase1),
    APPEARANCETOAWARDENELIDINISPHASE1(NpcID.TOA_WARDEN_ELIDINIS_PHASE1, false, AnimationID.NPC_WARDENS_DORMANT01, AnimationID.NPC_WARDENS_WALK01, null, null, VarrockStrayCatsConfig::appearanceToaWardenElidinisPhase1),
    APPEARANCEMYQ4ABOMINATION(NpcID.MYQ4_ABOMINATION, false, AnimationID.MYQ4_ABOMINATION_IDLE, AnimationID.MYQ4_ABOMINATION_CRAWL, null, null, VarrockStrayCatsConfig::appearanceMyq4Abomination),
    APPEARANCEAGRITHNAAR(NpcID.AGRITH_NAAR, false, AnimationID.DEMON_UPDATE_READY, AnimationID.DEMON_UPDATE_WALK, null, null, VarrockStrayCatsConfig::appearanceAgrithNaar),
    APPEARANCEBIMGOLEMBOSS(NpcID.BIM_GOLEM_BOSS, false, AnimationID.ANCIENT_GUARDIAN_IDLE, AnimationID.ANCIENT_GUARDIAN_WALKING_2X2, null, null, VarrockStrayCatsConfig::appearanceBimGolemBoss),
    APPEARANCETROLLROMANCEARRGATTACKABLE(NpcID.TROLLROMANCE_ARRG_ATTACKABLE, false, AnimationID.TROLL_READY, AnimationID.TROLL_WALK, null, null, VarrockStrayCatsConfig::appearanceTrollromanceArrgAttackable),
    APPEARANCEBRAINBARRELCHEST(NpcID.BRAIN_BARREL_CHEST, false, AnimationID.BRAIN_BARRELCHEST_READY, AnimationID.BRAIN_BARRELCHEST_WALK, null, null, VarrockStrayCatsConfig::appearanceBrainBarrelChest),
    APPEARANCEBLACKKNIGHTTITAN(NpcID.BLACK_KNIGHT_TITAN, false, AnimationID.GIANT_READY, AnimationID.GIANT_WALK, null, null, VarrockStrayCatsConfig::appearanceBlackKnightTitan),
    APPEARANCEARENABOUNCER(NpcID.ARENA_BOUNCER, false, AnimationID.DOG_UPDATE_WOLF_READY, AnimationID.DOG_UPDATE_HELLHOUND_GODWARS_WALK, null, null, VarrockStrayCatsConfig::appearanceArenaBouncer),
    APPEARANCESHADOWMAJKHAZARD(NpcID.SHADOW_MAJ_KHAZARD, false, AnimationID.MAHJARRAT_IDLE02, AnimationID.MAHJARRAT_WALK_FORWARD02, null, null, VarrockStrayCatsConfig::appearanceShadowMajKhazard),
    APPEARANCECHRONOZON(NpcID.CHRONOZON, false, AnimationID.DEMON_READY, AnimationID.DEMON_WALK, null, null, VarrockStrayCatsConfig::appearanceChronozon),
    APPEARANCESHAYZIENQUESTLIZARDMANBOSS(NpcID.SHAYZIENQUEST_LIZARDMAN_BOSS, false, AnimationID.SHAY_LIZARD_WARRIOR_READY, AnimationID.SHAY_LIZARD_WARRIOR_WALK, null, null, VarrockStrayCatsConfig::appearanceShayzienquestLizardmanBoss),
    APPEARANCECOUNTDRAYNOR(NpcID.COUNT_DRAYNOR, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceCountDraynor),
    APPEARANCEHUNDREDCULINAROMANCERBASE(NpcID.HUNDRED_CULINAROMANCER_BASE, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceHundredCulinaromancerBase),
    APPEARANCEFROGQUESTCUTHBERTNAMED(NpcID.FROG_QUEST_CUTHBERT_NAMED, false, AnimationID.GIANT_FROG_READY, AnimationID.GIANT_FROG_WALK, null, null, VarrockStrayCatsConfig::appearanceFrogQuestCuthbertNamed),
    APPEARANCETROLLCHAMPION(NpcID.TROLL_CHAMPION, false, AnimationID.TROLL_READY_SWORD, AnimationID.TROLL_WALK_SWORD, null, null, VarrockStrayCatsConfig::appearanceTrollChampion),
    APPEARANCEDELRITH(NpcID.DELRITH, false, AnimationID.DEMON_READY, AnimationID.DEMON_WALK, null, null, VarrockStrayCatsConfig::appearanceDelrith),
    APPEARANCEELVARGALIVE(NpcID.ELVARG_ALIVE, false, -1, -1, null, null, VarrockStrayCatsConfig::appearanceElvargAlive),
    APPEARANCEDEALEVILSPIRIT(NpcID.DEAL_EVIL_SPIRIT, false, AnimationID.SPIRIT_READY, AnimationID.SPIRIT_WALK, null, null, VarrockStrayCatsConfig::appearanceDealEvilSpirit),
    APPEARANCEDARKSEREN(NpcID.DARK_SEREN, false, AnimationID.DARK_LORD_READY, AnimationID.DARK_LORD_READY, null, null, VarrockStrayCatsConfig::appearanceDarkSeren),
    APPEARANCEBURGHGADDERANKS(NpcID.BURGH_GADDERANKS, false, AnimationID.BARROW_DHAROK_READY, AnimationID.BARROW_DHAROK_WALK, null, null, VarrockStrayCatsConfig::appearanceBurghGadderanks),
    APPEARANCEGALVEKWAVES(NpcID.GALVEK_WAVES, false, AnimationID.GALVEK_GROUNDED_READY, AnimationID.GALVEK_GROUNDED_READY, null, null, VarrockStrayCatsConfig::appearanceGalvekWaves),
    APPEARANCEMYARMGIANTROC(NpcID.MYARM_GIANT_ROC, false, AnimationID.MYARM_ROC_READY, AnimationID.MYARM_ROC_WALK, null, null, VarrockStrayCatsConfig::appearanceMyarmGiantRoc),
    APPEARANCECONTACTSCARABBOSS(NpcID.CONTACT_SCARAB_BOSS, false, AnimationID.CONTACT_BOSS_READY, AnimationID.CONTACT_BOSS_WALK, null, null, VarrockStrayCatsConfig::appearanceContactScarabBoss),
    APPEARANCEROYALSEASNAKEMOTHERSMALLER(NpcID.ROYAL_SEA_SNAKE_MOTHER_SMALLER, false, AnimationID.ROYAL_SEA_SNAKE_MOTHER_READY, AnimationID.ROYAL_SEA_SNAKE_MOTHER_READY, null, null, VarrockStrayCatsConfig::appearanceRoyalSeaSnakeMotherSmaller),
    APPEARANCEGRIMGLOD(NpcID.GRIM_GLOD, false, AnimationID.GRIM_GIANT_READY, AnimationID.GRIM_GIANT_WALK, null, null, VarrockStrayCatsConfig::appearanceGrimGlod),
    APPEARANCEFRISTROLLKINGTRUE(NpcID.FRIS_TROLL_KING_TRUE, false, AnimationID.TROLL_READY, AnimationID.TROLL_WALK, null, null, VarrockStrayCatsConfig::appearanceFrisTrollKingTrue),
    APPEARANCECORSCURSNAVIGATOR(NpcID.CORSCURS_NAVIGATOR, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceCorscursNavigator),
    APPEARANCEMMDEMON(NpcID.MM_DEMON, false, AnimationID.DEMON_READY, AnimationID.DEMON_WALK, null, null, VarrockStrayCatsConfig::appearanceMmDemon),
    APPEARANCEARENAOGRE(NpcID.ARENA_OGRE, false, AnimationID.OGRE_READY, AnimationID.OGRE_WALK, null, null, VarrockStrayCatsConfig::appearanceArenaOgre),
    APPEARANCEVIKINGENEMY1(NpcID.VIKING_ENEMY1, false, AnimationID.HUMAN_STAFFREADY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceVikingEnemy1),
    APPEARANCEMYQ6LOWERNIELHURT(NpcID.MYQ6_LOWERNIEL_HURT, false, AnimationID.VYRELORD_DRAKAN_READY, AnimationID.VYRELORD_DRAKAN_WALK, null, null, VarrockStrayCatsConfig::appearanceMyq6LowernielHurt),
    APPEARANCEQUESTLUNARMIRROROFPLAYER(NpcID.QUEST_LUNAR_MIRROR_OF_PLAYER, false, AnimationID.HUMAN_STAFFREADY, AnimationID.HUMAN_HALBERDWALK_F, null, null, VarrockStrayCatsConfig::appearanceQuestLunarMirrorOfPlayer),
    APPEARANCEMELZARTHEMAD(NpcID.MELZAR_THE_MAD, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceMelzarTheMad),
    APPEARANCEROVINGMOSSGIANT(NpcID.ROVING_MOSSGIANT, false, AnimationID.GIANT_UPDATE_MOSS_READY, AnimationID.GIANT_UPDATE_MOSS_WALK, null, null, VarrockStrayCatsConfig::appearanceRovingMossgiant),
    APPEARANCENEZIKCHENED(NpcID.NEZIKCHENED, false, AnimationID.DEMON_READY, AnimationID.DEMON_WALK, null, null, VarrockStrayCatsConfig::appearanceNezikchened),
    APPEARANCEMYQ3RANISDRAKAN(NpcID.MYQ3_RANIS_DRAKAN, false, AnimationID.MYQ3_VAMPIRE_GROUNDED_READY_MALE, AnimationID.MYQ3_VAMPIRE_GROUNDED_WALK, null, null, VarrockStrayCatsConfig::appearanceMyq3RanisDrakan),
    APPEARANCEHOSIDIUSQUESTSNAKE(NpcID.HOSIDIUSQUEST_SNAKE, false, AnimationID.ROYAL_SEA_SNAKE_READY, AnimationID.ROYAL_SEA_SNAKE_WALK_BABY, null, null, VarrockStrayCatsConfig::appearanceHosidiusquestSnake),
    APPEARANCESWANSEATROLLQUEEN(NpcID.SWAN_SEATROLL_QUEEN, false, AnimationID.SWAN_QUEEN_READY, -1, null, null, VarrockStrayCatsConfig::appearanceSwanSeatrollQueen),
    APPEARANCEDTTDSIGMUNDMILL(NpcID.DTTD_SIGMUND_MILL, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceDttdSigmundMill),
    APPEARANCERDCOMBATNPCROOM3(NpcID.RD_COMBAT_NPC_ROOM_3, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceRdCombatNpcRoom3),
    APPEARANCESIRMORDRED(NpcID.SIR_MORDRED, false, AnimationID.FAI_VARROCK_GUARD_READY, AnimationID.FAI_VARROCK_GUARD_WALK, null, null, VarrockStrayCatsConfig::appearanceSirMordred),
    APPEARANCESLAGILITH(NpcID.SLAGILITH, false, AnimationID.ROCK_READY, AnimationID.ROCK_WALK, null, null, VarrockStrayCatsConfig::appearanceSlagilith),
    APPEARANCEZOGRESLASHBASH(NpcID.ZOGRE_SLASH_BASH, false, AnimationID.OGRE_READY, AnimationID.OGRE_WALK, null, null, VarrockStrayCatsConfig::appearanceZogreSlashBash),
    APPEARANCESOULBANETOLNA(NpcID.SOULBANE_TOLNA, false, AnimationID.WAKE_UP_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceSoulbaneTolna),
    APPEARANCEHAUNTEDMINEBOSSGHOST(NpcID.HAUNTEDMINE_BOSS_GHOST, false, AnimationID.GHOST_UPDATE_TENDRILL_READY, AnimationID.GHOST_UPDATE_TENDRILL_WALK, null, null, VarrockStrayCatsConfig::appearanceHauntedmineBossGhost),
    APPEARANCEOLAF2ULFRIC(NpcID.OLAF2_ULFRIC, false, AnimationID.OLAF2_UNDEAD_READY, AnimationID.OLAF2_UNDEAD_WALK, null, null, VarrockStrayCatsConfig::appearanceOlaf2Ulfric),
    APPEARANCEELIDGOLEMBLACK(NpcID.ELID_GOLEM_BLACK, false, AnimationID.CLAY_GOLEM_READY, AnimationID.CLAY_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceElidGolemBlack),
    APPEARANCEELIDGOLEMGREY(NpcID.ELID_GOLEM_GREY, false, AnimationID.CLAY_GOLEM_READY, AnimationID.CLAY_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceElidGolemGrey),
    APPEARANCEELIDGOLEMWHITE(NpcID.ELID_GOLEM_WHITE, false, AnimationID.CLAY_GOLEM_READY, AnimationID.CLAY_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceElidGolemWhite),
    APPEARANCEBLOODDIAMONDVAMPIREWARRIOR(NpcID.BLOODDIAMOND_VAMPIREWARRIOR, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceBlooddiamondVampirewarrior),
    APPEARANCEICEDIAMONDICEWARRIOR(NpcID.ICEDIAMOND_ICEWARRIOR, false, AnimationID.HUMAN_TRANSREADY, AnimationID.HUMAN_TRANSWALK_F, null, null, VarrockStrayCatsConfig::appearanceIcediamondIcewarrior),
    APPEARANCEFIREDIAMONDFIREWARRIOR(NpcID.FIREDIAMOND_FIREWARRIOR, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceFirediamondFirewarrior),
    APPEARANCEFDDAMISNORMAL(NpcID.FD_DAMIS_NORMAL, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceFdDamisNormal),
    APPEARANCEHUNDREDMINION1(NpcID.HUNDRED_MINION1, false, AnimationID.AGRITH_NANA_READY, AnimationID.AGRITH_NANA_WALK, null, null, VarrockStrayCatsConfig::appearanceHundredMinion1),
    APPEARANCEHUNDREDMINION2(NpcID.HUNDRED_MINION2, false, AnimationID.ROCK_READY, AnimationID.ROCK_WALK, null, null, VarrockStrayCatsConfig::appearanceHundredMinion2),
    APPEARANCEHUNDREDMINION3(NpcID.HUNDRED_MINION3, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceHundredMinion3),
    APPEARANCEHUNDREDMINION4(NpcID.HUNDRED_MINION4, false, AnimationID.DESSOURT_READY, AnimationID.DESSOURT_WALK, null, null, VarrockStrayCatsConfig::appearanceHundredMinion4),
    APPEARANCEHUNDREDMINION5AIR(NpcID.HUNDRED_MINION5_AIR, false, AnimationID.HORROR_DAGANNOTH_READY, AnimationID.HORROR_DAGANNOTH_WALK, null, null, VarrockStrayCatsConfig::appearanceHundredMinion5Air),
    APPEARANCEDREAMINADEQUACY(NpcID.DREAM_INADEQUACY, false, AnimationID.DREAM_INADEQUACY_READY, AnimationID.DREAM_INADEQUACY_READY, null, null, VarrockStrayCatsConfig::appearanceDreamInadequacy),
    APPEARANCEDREAMEVERLASTING(NpcID.DREAM_EVERLASTING, false, AnimationID.DREAM_EVERLASTING_READY, AnimationID.DREAM_EVERLASTING_WALK, null, null, VarrockStrayCatsConfig::appearanceDreamEverlasting),
    APPEARANCEDREAMUNTOUCHABLE(NpcID.DREAM_UNTOUCHABLE, false, AnimationID.DREAM_UNTOUCHABLE_READY_WALK, AnimationID.DREAM_UNTOUCHABLE_READY_WALK, null, null, VarrockStrayCatsConfig::appearanceDreamUntouchable),
    APPEARANCEDREAMILLUSIVE(NpcID.DREAM_ILLUSIVE, false, AnimationID.DREAM_ILLUSIVE_READY, AnimationID.DREAM_ILLUSIVE_WALK, null, null, VarrockStrayCatsConfig::appearanceDreamIllusive),
    APPEARANCEMMKRUK(NpcID.MM_KRUK, false, AnimationID.M_MONKEY_READY, AnimationID.M_MONKEY_DH_WALK, null, null, VarrockStrayCatsConfig::appearanceMmKruk),
    APPEARANCEMM2GENERALKOBCOMBAT(NpcID.MM2_GENERAL_KOB_COMBAT, false, AnimationID.TROLL_READY_SWORD_SHIELD, AnimationID.TROLL_WALK_SWORD_SHIELD, null, null, VarrockStrayCatsConfig::appearanceMm2GeneralKobCombat),
    APPEARANCEMM2CHIEFTANKEEFCOMBAT(NpcID.MM2_CHIEFTAN_KEEF_COMBAT, false, AnimationID.OGRE_READY, AnimationID.OGRE_WALK, null, null, VarrockStrayCatsConfig::appearanceMm2ChieftanKeefCombat),
    APPEARANCEDREAMROBERTCOMBAT(NpcID.DREAM_ROBERT_COMBAT, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceDreamRobertCombat),
    APPEARANCEREGICIDEEVILELF1(NpcID.REGICIDE_EVIL_ELF1, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceRegicideEvilElf1),
    APPEARANCESUROKSUROKTYPE1(NpcID.SUROK_SUROK_TYPE1, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceSurokSurokType1),
    APPEARANCEWGSBALANCEELEMENTAL(NpcID.WGS_BALANCE_ELEMENTAL, false, AnimationID.NPC_BALANCE_ELEMENTAL_FIRE_IDLE01, AnimationID.NPC_BALANCE_ELEMENTAL_FIRE_WALK01, null, null, VarrockStrayCatsConfig::appearanceWgsBalanceElemental),
    APPEARANCEVMQ2ITZLACOMBAT(NpcID.VMQ2_ITZLA_COMBAT, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceVmq2ItzlaCombat),
    APPEARANCECOAMASTABAGOLEM(NpcID.COA_MASTABA_GOLEM, false, AnimationID.COA_STONE_GOLEM_READY, AnimationID.COA_STONE_GOLEM_WALK, null, null, VarrockStrayCatsConfig::appearanceCoaMastabaGolem),
    APPEARANCEDOVARRAVCOMBAT(NpcID.DOV_ARRAV_COMBAT, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceDovArravCombat),
    APPEARANCEVMQ4TEMPLEGUARDBOSSPATROL(NpcID.VMQ4_TEMPLE_GUARD_BOSS_PATROL, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceVmq4TempleGuardBossPatrol),
    APPEARANCEVMQ4KEYSTONECHAMBERBOSSMAGIC(NpcID.VMQ4_KEYSTONE_CHAMBER_BOSS_MAGIC, false, AnimationID.HUMAN_STAFFREADY, AnimationID.HUMAN_HALBERDWALK_F, null, null, VarrockStrayCatsConfig::appearanceVmq4KeystoneChamberBossMagic),
    APPEARANCEVMQ4KEYSTONECHAMBERBOSSRANGED(NpcID.VMQ4_KEYSTONE_CHAMBER_BOSS_RANGED, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceVmq4KeystoneChamberBossRanged),
    APPEARANCEVMQ4CRYPTENNIUSBOSS(NpcID.VMQ4_CRYPT_ENNIUS_BOSS, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceVmq4CryptEnniusBoss),
    APPEARANCEVMQ4CRYPTMETZLINOOPS(NpcID.VMQ4_CRYPT_METZLI_NOOPS, false, AnimationID.HUMAN_STAFFREADY, AnimationID.HUMAN_HALBERDWALK_F, null, null, VarrockStrayCatsConfig::appearanceVmq4CryptMetzliNoops),
    APPEARANCESAFALAANWYRD(NpcID.SAFALAAN_WYRD, false, AnimationID.NPC_WYRD01_READY01, AnimationID.NPC_WYRD01_WALK01, null, null, VarrockStrayCatsConfig::appearanceSafalaanWyrd),
    APPEARANCEGARGBOSSDAWNPHASE1(NpcID.GARGBOSS_DAWN_PHASE1, false, AnimationID.GG_DAWN_FLY, AnimationID.GG_DAWN_FLY, null, null, VarrockStrayCatsConfig::appearanceGargbossDawnPhase1),
    APPEARANCERTICEKING(NpcID.RT_ICE_KING, false, AnimationID.ICE_GIANT_ELDRIC_KING_IDLE01, AnimationID.ICE_GIANT_ELDRIC_KING_WALK01, null, null, VarrockStrayCatsConfig::appearanceRtIceKing),
    APPEARANCEGRANDTREEGLOUGHBATTLE(NpcID.GRANDTREE_GLOUGH_BATTLE, false, AnimationID.GNOME_READY, AnimationID.GNOME_WALK, null, null, VarrockStrayCatsConfig::appearanceGrandtreeGloughBattle),
    APPEARANCEHORRORDAGGANOTHAIRA(NpcID.HORROR_DAGGANOTH_AIRA, false, AnimationID.HORROR_DAGANNOTH_EMERGE_A, AnimationID.HORROR_DAGANNOTH_EMERGE_A, null, null, VarrockStrayCatsConfig::appearanceHorrorDagganothAira),
    APPEARANCETREESPIRIT(NpcID.TREE_SPIRIT, false, AnimationID.GHOST_UPDATE_NORMAL_READY, AnimationID.GHOST_UPDATE_NORMAL_WALK, null, null, VarrockStrayCatsConfig::appearanceTreeSpirit),
    APPEARANCEVIKINGDRAUGEN(NpcID.VIKING_DRAUGEN, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceVikingDraugen),
    APPEARANCECHICKENQUESTEVILCHICKEN(NpcID.CHICKENQUEST_EVIL_CHICKEN, false, AnimationID.ROOSTERREADY, AnimationID.ROOSTERWALK, null, null, VarrockStrayCatsConfig::appearanceChickenquestEvilChicken),
    APPEARANCEDWARFROCKAVATARWARRIOR(NpcID.DWARF_ROCK_AVATAR_WARRIOR, false, AnimationID.ROCK_AVATAR_READY, AnimationID.ROCK_AVATAR_WALK, null, null, VarrockStrayCatsConfig::appearanceDwarfRockAvatarWarrior),
    APPEARANCEDWARFROCKAVATARARCHER(NpcID.DWARF_ROCK_AVATAR_ARCHER, false, AnimationID.ROCK_AVATAR_READY, AnimationID.ROCK_AVATAR_WALK, null, null, VarrockStrayCatsConfig::appearanceDwarfRockAvatarArcher),
    APPEARANCEDWARFROCKAVATARMAGE(NpcID.DWARF_ROCK_AVATAR_MAGE, false, AnimationID.ROCK_AVATAR_READY, AnimationID.ROCK_AVATAR_WALK, null, null, VarrockStrayCatsConfig::appearanceDwarfRockAvatarMage),
    APPEARANCELOTRTRANRAZORLORMUTANT(NpcID.LOTR_TRAN_RAZORLOR_MUTANT, false, AnimationID.LOTR_TARN_RAZORLOR_MUTANT_READY, AnimationID.LOTR_TARN_RAZORLOR_MUTANT_WALK, null, null, VarrockStrayCatsConfig::appearanceLotrTranRazorlorMutant),
    APPEARANCESHADOWMAJBOUNCER(NpcID.SHADOW_MAJ_BOUNCER, false, AnimationID.DOG_UPDATE_WOLF_READY, AnimationID.DOG_UPDATE_HELLHOUND_GODWARS_WALK, null, null, VarrockStrayCatsConfig::appearanceShadowMajBouncer),
    APPEARANCEBLACKDEMONSTRONGHOLDCAVE1(NpcID.BLACK_DEMON_STRONGHOLDCAVE_1, false, AnimationID.DEMON_READY, AnimationID.DEMON_WALK, null, null, VarrockStrayCatsConfig::appearanceBlackDemonStrongholdcave1),
    APPEARANCEBARBASSAULTPENQUEENNEW(NpcID.BARBASSAULT_PEN_QUEEN_NEW, false, AnimationID.BARBASSAULT_PENACNE_QUEEN_NEW_READY, AnimationID.BARBASSAULT_PENANCE_QUEEN_NEW_WALK, null, null, VarrockStrayCatsConfig::appearanceBarbassaultPenQueenNew),
    APPEARANCESOULWARSAVATARBLUE(NpcID.SOUL_WARS_AVATAR_BLUE, false, AnimationID.SNP_NATURE_BOSS_READY, AnimationID.SNP_NATURE_BOSS_WALK, null, null, VarrockStrayCatsConfig::appearanceSoulWarsAvatarBlue),
    APPEARANCESOULWARSAVATARRED(NpcID.SOUL_WARS_AVATAR_RED, false, AnimationID.SNP_FIRE_BOSS_READY, AnimationID.SNP_FIRE_BOSS_WALK, null, null, VarrockStrayCatsConfig::appearanceSoulWarsAvatarRed),
    APPEARANCEMM2DEMONGLOUGH(NpcID.MM2_DEMON_GLOUGH, false, AnimationID.GIANT_UPDATE_BASIC_READY, AnimationID.GIANT_UPDATE_BASIC_WALK, null, null, VarrockStrayCatsConfig::appearanceMm2DemonGlough),
    APPEARANCESOTEARIANWYNCOMBAT(NpcID.SOTE_ARIANWYN_COMBAT, false, AnimationID.HUMAN_READY, AnimationID.HUMAN_WALK_F, null, null, VarrockStrayCatsConfig::appearanceSoteArianwynCombat),
    APPEARANCEWISEOLDMAN(NpcID.WISE_OLD_MAN, false, AnimationID.HUMAN_STAFFREADY, AnimationID.WALK_WALKINGSTICK, null, null, VarrockStrayCatsConfig::appearanceWiseOldMan),
    APPEARANCEBOB(NpcID.DS2_MEETING_BOB, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceBob),
    APPEARANCEEVILBOB(NpcID.MACRO_EVIL_BOB_OUTSIDE, false, AnimationID.CAT_READY, AnimationID.CAT_WALK, null, null, VarrockStrayCatsConfig::appearanceEvilBob),
    APPEARANCEITEMCABBAGE(ItemID.CABBAGE, true, -1, -1, null, null, VarrockStrayCatsConfig::appearanceItemCabbage),
    APPEARANCEGIANTCABBAGE(ItemID.CABBAGE, true, -1, -1, null, null, 200, VarrockStrayCatsConfig::appearanceGiantCabbage),
    APPEARANCEITEMFISHBOWLBLUEFISH(ItemID.FISHBOWL_BLUEFISH, true, -1, -1, null, null, VarrockStrayCatsConfig::appearanceItemFishbowlBluefish),
    APPEARANCEITEMFISHBOWLGREENFISH(ItemID.FISHBOWL_GREENFISH, true, -1, -1, null, null, VarrockStrayCatsConfig::appearanceItemFishbowlGreenfish),
    APPEARANCEITEMFISHBOWLSPINEFISH(ItemID.FISHBOWL_SPINEFISH, true, -1, -1, null, null, VarrockStrayCatsConfig::appearanceItemFishbowlSpinefish);

    final int definitionId;
    final boolean item;
    final int idleAnimation;
    final int walkAnimation;
    final short[] textureFrom;
    final short[] textureTo;
    final int targetHeight;
    private final Predicate<VarrockStrayCatsConfig> selected;

    AppearanceVariant(int definitionId, boolean item, int idleAnimation, int walkAnimation,
        short[] textureFrom, short[] textureTo, Predicate<VarrockStrayCatsConfig> selected)
    {
        this(definitionId, item, idleAnimation, walkAnimation, textureFrom, textureTo, 0, selected);
    }

    AppearanceVariant(int definitionId, boolean item, int idleAnimation, int walkAnimation,
        short[] textureFrom, short[] textureTo, int targetHeight, Predicate<VarrockStrayCatsConfig> selected)
    {
        this.definitionId = definitionId;
        this.item = item;
        this.idleAnimation = idleAnimation;
        this.walkAnimation = walkAnimation;
        this.textureFrom = textureFrom;
        this.textureTo = textureTo;
        this.targetHeight = targetHeight;
        this.selected = selected;
    }

    static AppearanceVariant choose(int originalNpcId, VarrockStrayCatsConfig config, Random random)
    {
        if (!config.randomBreeds() || (originalNpcId == NpcID.XMAS24_STRAYDOG_FINAL && !config.replaceDuke()))
        {
            return null;
        }
        List<AppearanceVariant> favorites = new ArrayList<>();
        for (AppearanceVariant variant : values())
        {
            if (variant.selected.test(config))
            {
                favorites.add(variant);
            }
        }
        return favorites.isEmpty() ? null : favorites.get(random.nextInt(favorites.size()));
    }
}
