"""Emit Java checkbox catalogue and provenance table from reviewed JSON."""
import json, re
from pathlib import Path

ROOT=Path(__file__).resolve().parent.parent
JAVA=ROOT/'src/main/java/com/cornydonkeh/varrockstraycats'
entries=json.loads((ROOT/'tools/appearance-catalogue.json').read_text())
animations={int(v):k for k,v in re.findall(r'^\tpublic static final int (\w+) = (\d+);', (ROOT/'animation-ids-source.txt').read_text(),re.M)}
def animation(id):
    if id==-1:return '-1'
    if id not in animations:raise ValueError(f'Missing animation constant {id}')
    return 'AnimationID.'+animations[id]
def quoted(s):return json.dumps(s,ensure_ascii=False)
def array(s):
    if s=='null':return 'null'
    return 'new short[] {'+s.strip('[]')+'}'
sections=list(dict.fromkeys(e['section'] for e in entries))
sections.sort(key=lambda s:['Cats','Dogs','Pets','Bosses','Characters & cabbage'].index(s.split(':')[0]))
section_keys={s:'section'+str(i) for i,s in enumerate(sections)}
config='''package com.cornydonkeh.varrockstraycats;

import net.runelite.client.config.Config;
import net.runelite.client.config.ConfigGroup;
import net.runelite.client.config.ConfigItem;
import net.runelite.client.config.ConfigSection;

// Generated by tools/generate_java.py; saved keys from the original plugin are preserved.
@ConfigGroup(VarrockStrayCatsConfig.GROUP)
public interface VarrockStrayCatsConfig extends Config
{
    String GROUP = "varrockstraycats";
    String LEGACY_GROUP = "healthydogs";
    String HEAL_VARROCK_DOGS = "healVarrockStray";

    @ConfigItem(keyName = HEAL_VARROCK_DOGS, name = "Enable appearances", description = "Heal Varrock's strays and Duke, or use checked favorite appearances. Cosmetic changes are local to your client.", position = 0)
    default boolean healVarrockDogs() { return true; }

    @ConfigItem(keyName = "randomBreeds", name = "Random favorite appearances", description = "Choose equally from checked cats, dogs, pets, bosses, Wise Old Man and cabbage. With none checked, use healthy dogs.", position = 1)
    default boolean randomBreeds() { return false; }

    @ConfigItem(keyName = "replaceDuke", name = "Include Duke in favorites", description = "Let Duke use checked favorites too. Disabled: Duke always keeps his healthy appearance.", position = 2)
    default boolean replaceDuke() { return false; }

'''
config += '    String[] LEGACY_KEYS = {\n        "healVarrockStray", "randomBreeds", "replaceDuke",\n'
config += ',\n'.join('        '+quoted(e['key']) for e in entries)+'\n    };\n\n'
for i,s in enumerate(sections):
    sk=section_keys[s]
    # Reuse original section identifiers for dog breed sections as well.
    original_dog_sections = {'Bernese Mountain Dog':'bernese','Border Collie':'borderCollie','Chihuahua':'chihuahua','Corgi':'corgi','Greyhound':'greyhound','Husky':'husky','Labrador':'labrador','Pug':'pug','Samoyed':'samoyed','Shiba':'shiba','Spaniel':'spaniel','Yorkie':'yorkie'}
    section_id = original_dog_sections.get(s.removeprefix('Dogs: '), sk)
    config+=f'    @ConfigSection(name = {quoted(s)}, description = {quoted("Favorite appearances: "+s)}, position = {10+i}, closedByDefault = true)\n    String {sk} = "{section_id}";\n\n'
    for pos,e in enumerate(x for x in entries if x['section']==s):
        config+=f'    @ConfigItem(keyName = "{e["key"]}", name = {quoted(e["label"])}, description = {quoted("Include "+e["label"]+" in random appearances.")}, section = {sk}, position = {pos})\n    default boolean {e["key"]}() {{ return false; }}\n\n'
config+='}\n'
(JAVA/'VarrockStrayCatsConfig.java').write_text(config,encoding='utf-8')
enum='''package com.cornydonkeh.varrockstraycats;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.function.Predicate;
import net.runelite.api.gameval.AnimationID;
import net.runelite.api.gameval.ItemID;
import net.runelite.api.gameval.NpcID;

/** Generated offline from a reviewed cache catalogue; see docs/appearances.md. */
enum AppearanceVariant
{
'''
for i,e in enumerate(entries):
    textures=e['textures'].split(':')
    enum+=f'    {e["key"].upper()}({"ItemID" if "itemId" in e else "NpcID"}.{e["symbol"]}, {str("itemId" in e).lower()}, {animation(e["idle"])}, {animation(e["walk"])}, {array(textures[0])}, {array(textures[1])}, VarrockStrayCatsConfig::{e["key"]})'+(';' if i==len(entries)-1 else ',')+'\n'
enum+='''
    final int definitionId;
    final boolean item;
    final int idleAnimation;
    final int walkAnimation;
    final short[] textureFrom;
    final short[] textureTo;
    private final Predicate<VarrockStrayCatsConfig> selected;

    AppearanceVariant(int definitionId, boolean item, int idleAnimation, int walkAnimation,
        short[] textureFrom, short[] textureTo, Predicate<VarrockStrayCatsConfig> selected)
    {
        this.definitionId = definitionId;
        this.item = item;
        this.idleAnimation = idleAnimation;
        this.walkAnimation = walkAnimation;
        this.textureFrom = textureFrom;
        this.textureTo = textureTo;
        this.selected = selected;
    }

    static AppearanceVariant choose(int originalNpcId, VarrockStrayCatsConfig config, Random random)
    {
        if (!config.randomBreeds() || (originalNpcId == NpcID.XMAS24_STRAYDOG_FINAL && !config.replaceDuke()))
        {
            return null;
        }
        List<AppearanceVariant> favorites = new ArrayList<>();
        for (AppearanceVariant variant : values())
        {
            if (variant.selected.test(config))
            {
                favorites.add(variant);
            }
        }
        return favorites.isEmpty() ? null : favorites.get(random.nextInt(favorites.size()));
    }
}
'''
(JAVA/'AppearanceVariant.java').write_text(enum,encoding='utf-8')
doc='''# Appearance catalogue

Based on [Healthy Stray Varrock Dogs](https://github.com/CornyDonkeh/healthy-stray-varrock-dogs),
with the original healing/rendering approach and saved dog option keys preserved.

Catalogue generated on 2026-10-03 from a workspace copy of the OSRS game cache,
cross-checked against the [OSRS pet list](https://oldschool.runescape.wiki/w/Pet)
and [boss list](https://oldschool.runescape.wiki/w/Boss), using RuneLite gameval constants.
Idle/walk animations and retextures below come from each model's own cache definition.
No runtime cache files are read or edited and no runtime network requests are added.

All follower pets in this cache are included, excluding quest companions Zanik, Nieve
and Grubfoot. Cats include all seven coats across kitten, adult, overgrown, lazy and
wily stages. Pet fish use inventory models; spooky chair and Mayor of Catherby use
their menagerie NPC models because they have no normal follower model definition.
Boss entries cover world, Wilderness, Slayer, raid, minigame and quest bosses with
available NPC models. Wintertodt has no standalone NPC model in this cache and
therefore is not a selectable appearance. Historical event bosses whose models
are absent are also excluded. Multipart bosses use their principal NPC model.

Large boss models keep their native scale. The NPC rendering callback hides the
original model and its 3D clickbox; replacements do not add pet interactions.
Static pets, fishbowls and cabbage follow the stray without an animation.

## Rebuilding

Run `gradlew.bat -p tools run --args="cache npcs.tsv"` against a COPY of the game
cache in `tools/cache/`. Save RuneLite gameval sources as `npc-ids-source.txt`,
`animation-ids-source.txt`, `item-ids-source.txt`, and wiki raw pet/boss lists as
`pets-wiki.txt` / `bosses-wiki.txt` in the workspace root. Then run
`python tools/build_catalogue.py` and `python tools/generate_java.py`.
Run `tools/fetch-boss-ids.ps1` to refresh the optional per-boss wiki ID cross-check.
Review `tools/appearance-catalogue.json` before generating Java. Sleeping, dead,
cutscene and other inactive models are deprioritized when choosing boss models.

## Choices

'''
for s in sections:
    doc+='### '+s+'\n\n| Checkbox | Definition | Idle | Walk |\n| --- | --- | --- | --- |\n'
    for e in entries:
        if e['section']==s:
            doc+=f'| {e["label"]} | {"ItemID" if "itemId" in e else "NpcID"}.{e["symbol"]} ({e.get("npcId",e.get("itemId"))}) | {e["idle"]} | {e["walk"]} |\n'
    doc+='\n'
(ROOT/'docs/appearances.md').write_text(doc,encoding='utf-8')
print(f'Generated {len(entries)} checkboxes in {len(sections)} sections.')
